### ISSUE TITLE
GUI unresponsive

### ISSUE THREAD

**Issue by mike-lloyd03** [sezanzeb/key-mapper#10]
I'm trying to set up my keyboard where holding capslock and typing h, j, k, or l will move left, down, up, or right as in vim. The only way I can think to do this is with a custom shortcut like alt-control-h. Is there a way to assign multiple modifiers to a key like alt-control to capslock?

Alternatively, is there a way to create a unique modifier key to use for something like this?

**Comment by sezanzeb** [comment]
Combining keys is on the todo list. You are the third person to ask, so It's most likely the next feature to be added, possibly in a few weeks.

**Comment by mike-lloyd03** [comment]
I'm using it on Arch and I've had a few issues with the program locking up. I'm not getting any error messages, just becomes unresponsive. I actually found a way to do what I'm looking for using `xmodmap` directly.

**Comment by sezanzeb** [comment]
what's the last thing that is being logged with `sudo key-mapper-gtk -d` before it becomes unresponsive?

**Comment by sezanzeb** [comment]
if you would map a combination of keys, for example a + b + c, would you expect b + a + c to trigger the same mapping? Or to be something different?

I need to write some more tests, but combining stuff is almost done. What's your use case?

Thanks.

**Comment by sezanzeb** [comment]
Combinations are released. I'll adjust the issue title to fit the freezing problem.
