### ISSUE TITLE
Feature Request: Distinction between mouse press and mouse release.

### ISSUE THREAD

**Issue by xioren** [sezanzeb/key-mapper#100]
By default Linux registers these actions as two separate events. For example pressing down right mouse button might open a context menu and releasing right mouse button selects the highlighted menu option. It would be extremely useful to control or toggle mouse click AND mouse release instead of "button LEFT" or "button RIGHT" as a whole.

e.g. "button LEFT CLICK", "button LEFT RELEASE"

**Comment by sezanzeb** [comment]
`k(a).h().k(b)` writes "a" on press and "b" on release. Does that do what you need?

**Comment by xioren** [comment]
So is there a way to unmap "release" when right clicking?

**Comment by sezanzeb** [comment]
unmap? as in disabling the release event?

your key would be stuck in autorepeat forever. It would be like keeping your finger on your "a" key on your keyboard

**Comment by xioren** [comment]
Right I mean register the release but not have it perform any action. Using the example in the op, by default in Linux right clicking opens a context menu and releasing selects whatever option your cursor is over. So I want to right click and release to open a context menu but not select anything; this is the default behavior in Windows.

**Comment by sezanzeb** [comment]
This is subject to the environment that implements the context menu. All key-mapper does is injecting event codes, it can't control how applications interpret them.

**Comment by xioren** [comment]
Okay, yeah I assume x-org xserver handles it. Thanks anyway.

**Comment by sezanzeb** [comment]
> Okay, yeah I assume x-org xserver handles it. Thanks anyway.

most likely GTK or Qt
