### ISSUE TITLE
Toggle on/off script needed

### ISSUE THREAD

**Issue by pascualpobil** [sezanzeb/key-mapper#104]
Hello I'm new here. I've been setting a couple of keys to be able to scroll and click using keys 'u', 'i', 'j' and 'k' given that I'm using a pointing stick to move my cursor. I'm using Linux mint and I want to use a custom shortcut to toggle the mapping on and off but cant find my way on doing so. All I need is the commands that performs the actions 'Restore Defaults' and 'Apply', so that i can go to the shortcuts in Mint and bind that action to something like 'Alt + O'. Any ideas ??? Thanks in advance.

**Comment by pascualpobil** [comment]
I've managed to set a layer using my space key but i have to use my right click on the pad due to the fact that i cant combine devices to make proper shortcuts.

I'd like to be able to make shortcuts combining the keys on my mousepad with the keys on my keyboard so that i don't have to use my space as the modifier. Please help, this is the last thing i need to set my laptop in a really proper way. Using this button is killing me when i write.

**Comment by sezanzeb** [comment]
> commands that performs the actions 'Restore Defaults' and 'Apply'

https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md#cli

> shortcuts combining the keys on my mousepad with the keys on my keyboard

currently not possible, injections are separate processes with their own state

**Comment by pascualpobil** [comment]
Thank you so much for the fast reply. I think the ref u gave me can solve all my problems. I'll give that a try and will come back to confirm!

**Comment by pascualpobil** [comment]
It works perfectly. This is all i needed. Thank you so much again, deeply appreciated.

**Comment by sezanzeb** [comment]
you're welcome

**Comment by sezanzeb** [comment]
> I'd like to be able to make shortcuts combining the keys on my mousepad with the keys on my keyboard

this is possible with macros now: https://github.com/sezanzeb/key-mapper/blob/main/readme/macros.md#combinations-spanning-multiple-devices for combinations

**Comment by pascualpobil** [comment]
After downloading last version it is working !!!!!!! Awesome. Thank u very much.
