### ISSUE TITLE
Cannot generate Mouse Button Events

### ISSUE THREAD

**Issue by igor-stoppa** [sezanzeb/key-mapper#112]
I have a mouse (Logitech G502) where the wheel is also the middle button.
It also happens to have several unused buttons (Button EXTRA, Button SIDE, etc.)
I would like to use one of these extra buttons to emulate the middle mouse button.

The Mapped functionality doesn't have the "Button MIDDLE" button option. (Nor the others)

**Comment by sezanzeb** [comment]
have you tried `BTN_MIDDLE`?

**Comment by sezanzeb** [comment]
Feel free to reopen this if you are still facing issues
