### ISSUE TITLE
Improve README - add note regarding policykit

### ISSUE THREAD

**Issue by jose1711** [sezanzeb/key-mapper#115]
A need to type password (or prepend with `sudo`) can be annoying. I think it would be great if README lists a quick way how to solve is using policykit. E. g. something like:

> In order to prevent `key-mapper` from asking the admin password on each run you can place the following lines into `/etc/polkit-1/rules.d/10-keymapper.rules` on your system:
> ```
> /* Allow users in games group to run key-mapper-gtk without authentication */
> polkit.addRule(function(action, subject) {
>     if (action.id == "keymapper" &&
>         subject.isInGroup("games")) {
>         return polkit.Result.YES;
>     }
> });
> ```

**Comment by sezanzeb** [comment]
that would allow running the helper as root without authentication, basically activating a key-logger. Not sure if this compromises the security too much

**Comment by jose1711** [comment]
True, OTOH it's pretty much the same as doing `NOPASSWD` in `sudoers` and as always it is assumed that user is responsible for security settings of the system.

**Comment by wenliang** [comment]
polkit >= 0.106 to support `.rules`.

ubuntu 20.04 is still using polkit 0.105, which only support `.pkla` format. 
not the `.rules` format above.

I create a `.pkla` file following https://www.freedesktop.org/software/polkit/docs/0.105/pklocalauthority.8.html
and it works.
