### ISSUE TITLE
Fails to run without policykit?

### ISSUE THREAD

**Issue by reidevries** [sezanzeb/key-mapper#117]
Installed it from AUR, I don't have a graphical polkit authentication agent, and the program fails to run. I'm using sway/wayland on Arch.

Here is the output from typing `key-mapper-gtk` in terminal:
```
key-mapper-gtk 1.0.0 84549b26244ea14bf551a37ff9e4088f99305f6b https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0
<redacted>
Connected to the service
==== AUTHENTICATING FOR keymapper ====
Authentication is required to discover and read devices.
Authenticating as: <me>
Password:
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
ERROR: Failed to pkexec the helper, code 32512
```

Here is the output from typing `sudo key-mapper-gtk`:
```
Authorization required, but no authorization protocol specified
Unable to init server: Could not connect: Connection refused
Authorization required, but no authorization protocol specified
Unable to init server: Could not connect: Connection refused
Authorization required, but no authorization protocol specified
Unable to init server: Could not connect: Connection refused

(key-mapper-gtk:57096): Gtk-WARNING **: 19:01:17.789: cannot open display: :0
```

It looks [similar to this issue in NixOs](https://github.com/NixOS/nixpkgs/issues/18012). I solved it using this [suggestion from another issue](https://github.com/sezanzeb/key-mapper/issues/115).

**Comment by jose1711** [comment]
I wonder if any other programs using policykit works on your system. Can you please check?

**Comment by reidevries** [comment]
> I wonder if any other programs using policykit works on your system. Can you please check?

Good call, Gparted is also not working with similar errors. 
(```
localuser:root being added to access control list
Error executing command as another user: No authentication agent found.
localuser:root being removed from access control list```) Something must have changed in my setup recently because I only used Gparted a few days ago and it worked fine.

**Comment by jose1711** [comment]
Yeah, perhaps you can try to check with Arch users on https://bbs.archlinux.org/ or IRC as this seems to be OS-related issue.

**Comment by reidevries** [comment]
Thanks, I'm gonna close this then I guess

**Comment by littlesandra88** [comment]
`sudo -E input-remapper-gtk` works for me.

https://github.com/swaywm/sway/issues/4492
