### ISSUE TITLE
How to edit pressed key without injecting

### ISSUE THREAD

**Issue by anonimo82** [sezanzeb/key-mapper#118]
Hello everyone.
I'm trying to map "Button Left Mouse Click" + "Volume Up", and "Button Left Mouse Click" + "Volume Down", to, respectively, map to "Button Right Mouse Click" and "Button Middle Mouse Click", but I can't edit the injected key - And it's not correctly detected, because the Mouse Click event is not shown in the field.
Now, I'm trying to do this with postmarketOS on a mobile phone, but, again, some keys are actually detected, so I guess I'm doing something wrong.
Can I edit the key to be mapped without injecting? How?
Or am I better manually inserting in the configuration file?

Thanks in advance for any help.

Regards =)

**Comment by sezanzeb** [comment]
Have you clicked on the "Restore Defaults" button on the top right before attempting to edit the mapping?

**Comment by anonimo82** [comment]
That button is greyed in my system

**Comment by sezanzeb** [comment]
As far as I remember clicking the button will still send a message to the daemon, even if it is greyed out.

> because the Mouse Click event is not shown in the field.

how do you make a mouse click in postmarketos?

**Comment by anonimo82** [comment]
By single tapping the screen

**Comment by anonimo82** [comment]
So, here's what I did so far:
- Open the Device in upper Menu
- Clicked on "click here"
- Pressed "VOLUMEUP"
- Wrote BTN_LEFT near
- Clicked "Apply"
- Got "Failed to apply preset"

What's wrong?

**Comment by anonimo82** [comment]
This morning I tried with VNC from my computer to my phone, I can send middle/right clicks, but, in example, I can't "capture" left/right click (didn't try with middle) with key-mapper, in any device listed.
So, what's wrong?

**Comment by sezanzeb** [comment]
the output of `sudo pkill -f key-mapper-service && key-mapper-gtk -d` when trying to apply the preset would be interesting, no idea how that works on your phone

**Comment by anonimo82** [comment]
I think I got it: I guess Phosh (the Window Manager I'm using) doesn't "know" what a Mouse and a Keyboard are, proof of this is I can click with a "regular" Mouse, but not send a click event, and neither binding some key to a Keyboard works, because (in a text editor, for example) no characters are written when pressing the bound Key.
So, I guess I need to install some kind of Mouse/Keyboard driver support (eg, Synaptics Touch Pad Driver).

I'll keep you posted, in the meantime, we can close this if you wish.

**Comment by sezanzeb** [comment]
I think I can't provide any real helpful support. dbus and evdev needs to be supported on the phone.

You can try if python-evdev works by following some examples on https://python-evdev.readthedocs.io/en/latest/usage.html#listing-accessible-event-devices
