### ISSUE TITLE
rc-service key-mapper start - rc-service: service `key-mapper' does not exist

### ISSUE THREAD

**Issue by anonimo82** [sezanzeb/key-mapper#122]
Please install the newest version from source to see if the problem has already been solved.
Yes, I installed right now with pip

Share some logs please:

1. `key-mapper-control --version`

`key-mapper 1.0.0 84549b26244ea14bf551a37ff9e4088f99305f6b https://github.com/sezanzeb/key-mapper python-evdev 1.4.0`

2. which linux distro (ubuntu 20.04, manjaro, etc.)

`postmarketOS edge (latest) on a SM-A500FU (Samsung Galaxy A5 2015)`

3. `echo $XDG_SESSION_TYPE`

`wayland`

4. which desktop environment (gnome, plasma, xfce4, etc.)

`Phosh`

5. `sudo ls -l /proc/1/exe`

`lrwxrwxrwx    1 root     root             0 Jun  7 03:46 /proc/1/exe -> /bin/busybox`

6. `cat ~/.config/key-mapper/config.json`

```
{
    "autoload": {},
    "macros": {
        "keystroke_sleep_ms": 10
    },
    "gamepad": {
        "joystick": {
            "non_linearity": 4,
            "pointer_speed": 80,
            "left_purpose": "none",
            "right_purpose": "none",
            "x_scroll_speed": 2,
            "y_scroll_speed": 0.5
        }
    }
}
```

7. `key-mapper-control --command hello`

```Found "samsung-a2015 Headset Jack", "tm2-touchkey", "GPIO Buttons", "pm8941_pwrkey"
ERROR: Service not running? g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name keymapper.Control was not provided by any .service files (2)```

8. `systemctl status key-mapper -n 50`

`Don't have that command available`

9. `sudo pkill -f key-mapper-service && sudo key-mapper-service -d & sleep 2 && key-mapper-control --command autoload`, are your keys mapped now?

`No output and no, keys aren't mapped`

10. (while the previous command is still running) `sudo evtest` and search for a device suffixed by "mapped". Select it, does it report any events? Share the output.

`Command above stops execution immediately, so I can't run anything else in the while`

My problem is, after installation, I can't run the service, as the service (apparently) doesn't exist.

**Comment by sezanzeb** [comment]
key-mapper supports systemd.

If you only run `sudo key-mapper-service -d`, what happens?

**Comment by anonimo82** [comment]
It started the daemon

**Comment by sezanzeb** [comment]
now in a separate terminal while the daemon is running, what does `key-mapper-control --command hello` do?

**Comment by anonimo82** [comment]
It says:```

Found "samsung-a2015 Headset Jack", "tm2-touchkey", "GPIO Buttons", "pm8941_pwrkey"
Connected to the service
Daemon answered with "hello"
```

**Comment by sezanzeb** [comment]
great, so the daemon is running and communication works.

if you use the interface now, does it work?

**Comment by anonimo82** [comment]
No, the volume key still raises the volume, while I'd like it to trigger BTN_RIGHT

**Comment by sezanzeb** [comment]
but at least you are able to run the service. you might be able to autostart it by adding that command somewhere on the system, no idea what postmarkedos supports for that. So this issue:

> My problem is, after installation, I can't run the service, as the service (apparently) doesn't exist.

can be closed now?

**Comment by sezanzeb** [comment]
getting key-mapper to run on something exotic like linux on a mobile phone is outside of the scope.

**Comment by anonimo82** [comment]
Ok, you can close this.
Thanks for:
- Your time
- Your patience
- Your help

Cheers =)

**Comment by anonimo82** [comment]
For the records, I had a Python error in console while trying to use the keys, but the daemon didn't stop, and using the volume key to right-click makes it impossible to left click, I have to restart the application.
Tested with Gimp, I can send the log if you wish. If you want to read it, please, just tell me where is it located.

**Comment by sezanzeb** [comment]
I don't think the log contains python tracebacks. /var/log/key-mapper

> a Python error in console while trying to use the keys

Can you copy and paste that one from the console please?

**Comment by anonimo82** [comment]
No, you're right, no Python errors.
Yes, I'll do tomorrow

**Comment by anonimo82** [comment]
Steps I've done so far:
- sudo key-mapper-service -d
- Open Gimp
- Touch keys for BTN_MIDDLE and BTN_RIGHT clicks (now bound to APPSELECT and BACK, respectively)
- Using VNC, copied the log below in a file
- Closed evertything

[keyMapperLog.txt](https://github.com/sezanzeb/key-mapper/files/6613538/keyMapperLog.txt)

Hope you can help me someway. By the way, the last time I tried to install, I did an "rc-service key-mapper start" and everything went fine, now I can't start the service in any way but launching key-mapper-service. Why?

Thanks in advance for any help. Cheers =)

**Comment by sezanzeb** [comment]
> Why?

no idea

> "/dev/uinput" does not exist or is not a character device file - verify that the uinput module is loaded

- https://www.kernel.org/doc/html/v4.12/input/uinput.html
- https://linux-kernel-labs.github.io/refs/heads/master/labs/kernel_modules.html

Run `modprobe uinput` and try again

**Comment by anonimo82** [comment]
You're so GREAT!!!
With module uinput, it works like a charm!
All I have to do now is loading the module and the service at startup.

Big thanks, you just made me happy =)

**Comment by sezanzeb** [comment]
you are welcome, glad it turned out it can indeed work :)

maybe `modprobe uinput` should be part of service startup

**Comment by anonimo82** [comment]
Yes, I agree
