### ISSUE TITLE
Multiple devices with same name share the same macros

### ISSUE THREAD

**Issue by TRPB** [sezanzeb/key-mapper#123]
This was discussed in #93 and the fix partially works: My two joysticks appear as two entries in the device list and they didn't in the earlier version. However, both devices share the same macro list.

If I choose "Thrustmaster T.16000M", add a mapping then choose "Thrustmaster T.16000M 2" the mapping for `1` is still shown in the list once `2` is selected and because key-mapper thinks there is already a binding set, I can't bind the same button on the other joystick. 

The problem is that the `2` isn't used when loading.

Here's what happens in the console if I select `1` then `2`:

```
Loading preset from "/home/tom/.config/key-mapper/presets/Thrustmaster T.16000M/new preset copy.json"
39693 70.4417 DEBUG helper.py:96: Received command "Thrustmaster T.16000M"
39693 70.4962 DEBUG helper.py:151: Starting reading keycodes from "Thrustmaster T.16000M"
Loading preset from "/home/tom/.config/key-mapper/presets/Thrustmaster T.16000M/new preset copy.json"
39693 79.9528 DEBUG helper.py:96: Received command "Thrustmaster T.16000M 2"
39693 80.0095 DEBUG helper.py:151: Starting reading keycodes from "Thrustmaster T.16000M"
```

Despite the second "Received command" line picking up the second joystick, it reads the keycodes without the `2` at the end and reads from the same directory (without the 2) as the first joystick.

I think it needs to use `device.phys` rather than `device.fd` throughout because `fd` is `12` for both of them in this instance.

**Comment by TRPB** [comment]
I'm trying to debug this but I'm not entirely sure where to look.

`helper.py:_start_reading` appears to be working fine, if I print out `device.phys` on line 175 it's correctly identifying different devices. I think the problem might just be the GUI not refreshing.

Should device 2 with the same name have its own folder/config file?

**Comment by sezanzeb** [comment]
First I'd check if the config files in `~/.config/key-mapper/presets` are correct

If they are, then check the `on_select_preset` function if it loads the correct file. https://github.com/sezanzeb/key-mapper/blob/main/keymapper/gui/window.py#L759

**Comment by TRPB** [comment]
I've fixed it for my purposes and can send a PR but I'm not sure I understand how groups are supposed to work.

To fix it, I've changed all calls to Mapping.load to use group.key instead of group.name.


`daemon.py`:
```
        preset_path = os.path.join(
            self.config_dir,
            'presets',
            group_key,
            f'{preset}.json'
        )

```

instead of    

```
        preset_path = os.path.join(
            self.config_dir,
            'presets',
            group.name,
            f'{preset}.json'
        )
```

and changed `groups.py`:

```

    def get_preset_path(self, preset=None):
        """Get a path to the stored preset, or to store a preset to.

        This path is unique per device-model, not per group. Groups
        of the same model share the same preset paths.
        """
        return get_preset_path(self.name, preset)
```

to

```

    def get_preset_path(self, preset=None):
        """Get a path to the stored preset, or to store a preset to.

        This path is unique per device-model, not per group. Groups
        of the same model share the same preset paths.
        """
        return get_preset_path(self.key, preset)
```

This has the result of giving each device its own folder/json file in the config directory and the GUI identifies the change when selecting the option.

I can add a PR with these changes but I'm not sure this is how it's intended? Are group bindings supposed to all be in the same file.

**Comment by sezanzeb** [comment]
oh yes sure of course, both devices use the same preset files on purpose. Otherwise you would have to copy the preset files from "device 2" to "device"

**Comment by TRPB** [comment]
so is it possible to have two devices of the same name with different mappings assigned? I can imagine plugging in two xbox controllers and wanting to play a game would require having different key mappings on each controller.

**Comment by sezanzeb** [comment]
yes, it should be possible to apply different mappings to each of the devices.

They share the same preset files though.

**Comment by TRPB** [comment]
At the moment if I associate BUTTON1 on one joystick, then select the other, BUTTON1 appears with a mapping already applied. If I change it, it changes it for both sticks. I want, for example, BUTTON1 on stick 1 to map to the `x` key and BUTTON1 on stick 2 to map to the `y` key. It doesn't seem to be possible to set that up without the change I made above.

**Comment by sezanzeb** [comment]
After selecting the second device, use the "Copy" button and change the button in the new preset. You should end up with two different presets.

Then apply preset 1 on joystick 1 and preset 2 on joystick 2

**Comment by TRPB** [comment]
ah, I get it now. Each device is given its own preset. Yes that makes sense.
