### ISSUE TITLE
Cursor not moving in postmarketos

### ISSUE THREAD

**Issue by anonimo82** [sezanzeb/key-mapper#125]
Hello everyone.
I can't start key-mapper service any longer, my system complaints saying it doesn't exist.
And, launching everything manually, the mouse cursor doesn't move anymore.
Did you change anything in the code lately?

**Comment by sezanzeb** [comment]
no, did not commit anything to the code since 1.0.0

key-mapper never had rc-init files, it always only supported systemd, so I doubt it ever started automatically.

> the mouse cursor doesn't move anymore.

Didn't it work yesterday?

**Comment by anonimo82** [comment]
Believe it or not, the first time I installed key-mapper I started the service successfully.
And the mouse was working.
Now, none of the above works well.

**Comment by anonimo82** [comment]
Ok, I can use key bindings, but I have to open the GUI and apply preset each boot.
Still the mouse cursor won't move

**Comment by sezanzeb** [comment]
does `sudo evtest` show EV_REL events that look correct?

**Comment by anonimo82** [comment]
output:
sudo: evtest: command not found

**Comment by sezanzeb** [comment]
and does it show EV_REL events?

**Comment by anonimo82** [comment]
No, just EV_KEY

**Comment by sezanzeb** [comment]
there might be multiple devices ending with "forwarded", did you try all of them?

**Comment by anonimo82** [comment]
Now yes, no device detects EV_REL events, but I have a device which reacts on touch screen

**Comment by sezanzeb** [comment]
please post the output of:

```
sudo python3
import evdev
for path in evdev.list_devices():
    device = evdev.InputDevice(path)
    print(device.name, device.capabilities(verbose=True).get(('EV_REL', 2)))
```

**Comment by anonimo82** [comment]
The same device list, with none after each

**Comment by sezanzeb** [comment]
that means none of your devices is currently able to send mouse movements to your smartphone, and key-mapper cannot do anything about that

**Comment by anonimo82** [comment]
Ok

**Comment by anonimo82** [comment]
I solved, the cursor still doesn't move, but right and middle click are triggered at last touched position.
I made it by creating /etc/X11/xorg.conf, with the following content:

```
Section "InputDevice"
        Identifier      "Syn"
        Driver          "libinput"
        Device          "/dev/input/event4"
        Option          "ClickMethod"   "clickfinger"
        Option          "Tapping"       "on"
EndSection

Section "Inputclass"
        Identifier      "Syn"
        Driver          "libinput"
        MatchIsTouchpad "on"
        Option          "Tapping"       "on"
        Option          "ClickMethod"   "clickfinger"
EndSection
```
