### ISSUE TITLE
Can't remap/detect side wheel buttons

### ISSUE THREAD

**Issue by rimko** [sezanzeb/key-mapper#13]
Key-mapper can't detect left wheel/ right wheel direction (REL_HWHEEL i think) i have caputre the result of evtest for each of my devices, with 2 key input each time, first left mouse wheel then right mouse wheel : 

- [Logitech MX Master 2S.txt](https://github.com/sezanzeb/key-mapper/files/5760125/Logitech.MX.Master.2S.txt)
- [Logitech MX Ergo.txt](https://github.com/sezanzeb/key-mapper/files/5760126/Logitech.MX.Ergo.txt)
- [ELECOM TrackBall Mouse HUGE TrackBall.txt](https://github.com/sezanzeb/key-mapper/files/5760127/ELECOM.TrackBall.Mouse.HUGE.TrackBall.txt)

Same result for the 3 devices:
`Testing ... (interrupt to exit)
Event: time 1609584164.206483, type 2 (EV_REL), code 6 (REL_HWHEEL), value -1
Event: time 1609584164.206483, type 2 (EV_REL), code 12 (REL_HWHEEL_HI_RES), value -120
Event: time 1609584164.206483, -------------- SYN_REPORT ------------
Event: time 1609584166.638449, type 2 (EV_REL), code 6 (REL_HWHEEL), value 1
Event: time 1609584166.638449, type 2 (EV_REL), code 12 (REL_HWHEEL_HI_RES), value 120
Event: time 1609584166.638449, -------------- SYN_REPORT ------------`

**Comment by sezanzeb** [comment]
Thanks, could you please betatest this branch and report back if it worked?

https://github.com/sezanzeb/key-mapper/tree/wheel-attempt-2

**Comment by rimko** [comment]
Hi,

No change for if i have test it the right way.
What I have done :
`git clone -b wheel-attempt-2 https://github.com/sezanzeb/key-mapper.git`
then
`cd key-mapper && sudo python3 setup.py install`

I have also try with erasing the config file and removing the previous installation folder, and them launch key-mapper-gtk on the terminal to see if there while be any output when i try to configure it but no result on my 3 devices.

By the way thank you, awesome project !

**Comment by sezanzeb** [comment]
the clone is correct.

installing via setup.py can be tricky. Which distro are you running? Try it again with `--force`. You'll be able to tell if the installation worked if using `shift + del` on your keyboard activates the `restore defaults` button.

**Comment by sezanzeb** [comment]
@rimko did you already have a chance to try it out?

**Comment by sojusnik** [comment]
Same here on a Logitech M590.
```
$ xev | grep button
    state 0x0, button 6, same_screen YES
    state 0x0, button 6, same_screen YES
    state 0x0, button 7, same_screen YES
    state 0x0, button 7, same_screen YES
```

**Comment by sezanzeb** [comment]
pushed to main now.

**Comment by rimko** [comment]
hi ! sorry for the delay.
I just try the release 6.0 and it works!  maybe it was my fault.

After upgrading i get issue issue with the service :
(resuslt of :  `systemctl status key-mapper.service` )
```
Warning: The unit file, source configuration file or drop-ins of key-mapper.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2021-01-08 10:58:40 CET; 12min ago
   Main PID: 870 (key-mapper-serv)
      Tasks: 3 (limit: 19075)
     Memory: 35.4M
        CPU: 248ms
     CGroup: /system.slice/key-mapper.service
             └─870 /usr/bin/python3 /usr/bin/key-mapper-service

janv. 08 11:09:54 dektop-wifi key-mapper-service[870]:   File "/usr/local/lib/python3.9/site-packages/keymapper/daemon.py", line 188, in start_injecting
janv. 08 11:09:54 dektop-wifi key-mapper-service[870]: IsADirectoryError: [Errno 21] Is a directory: '/home/rimko/.config/key-mapper'
janv. 08 11:10:10 dektop-wifi key-mapper-service[870]: Loaded config from "/home/root/.config/key-mapper/config.json"
janv. 08 11:10:10 dektop-wifi key-mapper-service[870]: Loading preset from "/home/rimko/.config/key-mapper/presets/ELECOM TrackBall Mouse HUGE TrackBall/main.json"
janv. 08 11:10:10 dektop-wifi key-mapper-service[870]: ERROR: Exception while handling keymapper.Control.start_injecting()
janv. 08 11:10:10 dektop-wifi key-mapper-service[870]: Traceback (most recent call last):
janv. 08 11:10:10 dektop-wifi key-mapper-service[870]:   File "/usr/local/lib/python3.9/site-packages/pydbus/registration.py", line 81, in call_method
janv. 08 11:10:10 dektop-wifi key-mapper-service[870]:     result = method(*parameters, **kwargs)
janv. 08 11:10:10 dektop-wifi key-mapper-service[870]:   File "/usr/local/lib/python3.9/site-packages/keymapper/daemon.py", line 188, in start_injecting
janv. 08 11:10:10 dektop-wifi key-mapper-service[870]: IsADirectoryError: [Errno 21] Is a directory: '/home/rimko/.config/key-mapper'
```

But after running `systemctl daemon-reload` everything works :) 

I have try the REL_HWHEEL L/R on all my devices ( MX Master 2S, MX Ergo, Elecom Huge) and it's works fine !

Thank you again ! :)

**Comment by sezanzeb** [comment]
ah yes, I should add systemctl to the readme for the pip installation.

nice
