### ISSUE TITLE
Document mapping field

### ISSUE THREAD

**Issue by slhck** [sezanzeb/key-mapper#135]
This is an awesome tool, thank you!

I just can't for the life of me find a documentation on what can be entered in to the "Mapping" field.

Is there a list of possible keys and modifiers available?

If not, it would be good to add this to the documentation.

**Comment by sezanzeb** [comment]
https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md

> You can also obtain a complete list of possiblities using key-mapper-control --symbol-names.

**Comment by slhck** [comment]
Oh I see. I think that is hard to discover because it's listed under "Key names".

Perhaps there could be a sentence like, after the screenshot on the top:

```
In "Mapping", type the key to which you would like to map this key. You can also use [combinations](#combinations) or [macros](#macros). For all possible key names, see [Key Names](#key-names)
```

**Comment by sezanzeb** [comment]
Looks good to me. Feel free to make a pull request if you want to add it yourself :)

**Comment by slhck** [comment]
PS: Would you happen to know which keys are needed to mimic the Back/Forward behavior that works all across the OS (e.g. navigating browser history, etc.)? Alt + Left and Alt + Right are not universal it seems.

**Comment by sezanzeb** [comment]
KEY_BACK and KEY_FORWARD

This would be easier to configure with https://github.com/sezanzeb/key-mapper/issues/136

**Comment by sezanzeb** [comment]
or BTN_EXTRA and BTN_SIDE

**Comment by slhck** [comment]
`BTN_EXTRA` and `BTN_SIDÈ` is what the mouse is reporting indeed, but they're not picked up properly by the OS. Adding `KEY_BACK` and `KEY_FORWARD` did the trick.
