### ISSUE TITLE
XCompose being ignored

### ISSUE THREAD

**Issue by jbsilva** [sezanzeb/key-mapper#145]
When I start the daemon, my mappings in ~/.XCompose are ignored.
After stopping the daemon, all gets back to normal.

**Comment by sezanzeb** [comment]
Key-mapper makes a new devices appear that injects the events that are being mapped to. Does the configuration in XCompose only apply to devices that have been plugged in at login-time? If so, then it also won't work for key-mapper. I guess it might be similar to xmodmap in that regard.

Maybe this helps: https://askubuntu.com/questions/1100084/how-to-reload-xcompose-without-a-reboot#1190099
