### ISSUE TITLE
Restrict mappings to specific applications

### ISSUE THREAD

**Issue by vanillajonathan** [sezanzeb/key-mapper#146]
I do not want all my mappings to be global and apply when using all applications.

Example when I am using gedit I might want one set of mappings,  but while using GNOME Terminal I might want another set of mappings.

**Comment by sezanzeb** [comment]
Not possible:

https://github.com/sezanzeb/key-mapper/discussions/20
https://github.com/sezanzeb/key-mapper/issues/56
https://github.com/sezanzeb/key-mapper/issues/32
https://github.com/sezanzeb/key-mapper/issues/50
