### ISSUE TITLE
Razer DeathAdder Elite Mapping Issues

### ISSUE THREAD

**Issue by purpleshadows** [sezanzeb/key-mapper#148]
Setup: 
-Manjaro.
-latest version of key-mapper installed with pip. 
-OpenRazer drivers.

Issue:
-Unable to map the middle mouse button and the DPI buttons.

**Comment by sezanzeb** [comment]
Please check out the issue template for that case: https://github.com/sezanzeb/key-mapper/blob/main/.github/ISSUE_TEMPLATE/buttons-not-showing-up---can-t-map-a-key-in-the-gui.md

**Comment by purpleshadows** [comment]
Odd. Middle mouse has an event and works now.

The two DPI buttons don't have an event assigned to them and are not responsive to evtest and key-mapper. 

Is it possible to implement them?

**Comment by sezanzeb** [comment]
Since I'm not a driver or hardware kind of developer I can't say anything about possibilities there, and it goes beyond what key-mapper would be able to do.
