### ISSUE TITLE
missing macro info ? coming back from #104

### ISSUE THREAD

**Issue by pascualpobil** [sezanzeb/key-mapper#151]
Hey, I'm back after some months (from issue #104) cos i didn't see your last response and i could manage to find a solution with the previous ones.

I've seen the reply where u say that combining mouse clicks with keyboard clicks to create mappings is possible, and I've been trying to find some info around the usage.md and the macro.md and got no luck.

I think the main problem is that i don't understand what 'foo' and 'bar' means. Haven't seen any macro examples with this syntax either and its being hard to figure out. I feel like i would need some more extended documentation on the whole topic.

If this helps, my current setup is an OS shortcut that enables a preset/layout.

The ideal would be not having to toggle on/off but instead being able to 'toggle on/off' using MOUSE2 as a modifier (which was no possible until u mentioned macros).

Something like:
MOUSE2+'h' = scroll down ;
MOUSE2+'u' = MOUSE1 ;
MOUSE2 + 'j' = MOUSE2 ;
MOUSE2 + 'i' = scroll up ;

and so on. Thanks in advance.

**Comment by sezanzeb** [comment]
foo and bar are placeholders for anything https://en.wikipedia.org/wiki/Foobar.

`set(foo, 1)` makes `ifeq(foo, 1, k(a), k(b))` write an a, just like `set(var, yes)` and `ifeq(var, yes, k(a), k(b))`. foo is a variable name that you call anything, and you can assign any value to it, like for example 1 or bar

**Comment by sezanzeb** [comment]
> I've been trying to find some info around the usage.md and the macro.md and got no luck.

"Combinations spanning multiple devices"

https://github.com/sezanzeb/key-mapper/blob/main/readme/macros.md#combinations-spanning-multiple-devices

**Comment by pascualpobil** [comment]
Ok so they are just 2 variable names that could be whatever. I thought they were parameters specific of the program.

With this in mind, are macros universal for every preset and device or u have a macro per preset or per device ? Is there any macro for a specific usage that I could have a look at ?

**Comment by sezanzeb** [comment]
> are macros universal for every preset and device or u have a macro per preset or per device ?

You can configure macros the exact same way as configuring a regular mapping. You can map `a` to `b` and `p` to `k(1).k(2)`. Is this what you meant? Just insert it into the mapping column of a specific preset.

> Is there any macro for a specific usage

whatever you need

**Comment by pascualpobil** [comment]
Okay i think i've got the idea.

So as i guess variables are global (shared between devices) when u map space to 'set(foo, bar).h(space).set(foo, 0)' foo will be bar until u release space, so u can use ifeq to make another mapping work only while while foo==bar. 

Cos set(foo, 0) only runs after h(space) is done and it will only finish after u release space. So i'm literally holding the value of the variable while i'm holding space.

Did i understand correctly ?

**Comment by sezanzeb** [comment]
yes

**Comment by pascualpobil** [comment]
I'm trying to use the set function on the mapping section but it keeps saying 'Unknown function set'.

One detail about 'set(foo, bar).h(space).set(foo, 0)' :
h(space) would write 'h' repeatedly until i release and then change foo to 0. If i write h().k(space) it waits for me to release and then writes space. 

As i'm gonna use M2 and i want M2 to do nothing else than work as modifier, i will just use:
          set(foo, 1).h().set(foo, 0)

But as i said, this is not working because i get 'Unknown function set'. This only happens with set(.......); h() and h(bar) both work fine.

**Comment by sezanzeb** [comment]
`key-mapper-control --version`?

**Comment by pascualpobil** [comment]
0.8.1 , gonna try updating

**Comment by pascualpobil** [comment]
After downloading last version it is working !!!!!!!!! Set and ifeq working as expected with multiple devices. I will update my setup if you don't mind in case anyone is looking for the same. Thank you very much !

**Comment by sezanzeb** [comment]
You're welcome
