### ISSUE TITLE
Layout is changed on Apply

### ISSUE THREAD

**Issue by SebiTimeWaster** [sezanzeb/key-mapper#152]
I use a US keyboard layout together with mixed British/German locales, and when i apply a mapping my keyboard layout is suddenly switched from US to German. 

When i click "Restore Defaults" everything is back to normal.

Second bug: Applying again does not work, no mapping is applied, even after restarting the application, did not try restarting the computer.

My locales:

LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

**Comment by sezanzeb** [comment]
key-mapper doesn't control the locale that is about to be applied on the new device. It just creates a new uinput and starts writing events into it. What the environment does after that is outside of key-mappers reach and I don't know the rules under which the environment (X/Gnome/KDE) decides to apply a different keyboard layout.

please run `sudo pkill -f key-mapper && key-mapper-gtk -d` and reproduce the problem that makes applying the presets again impossible. Share the logs afterwards

**Comment by SebiTimeWaster** [comment]
i moved on to a different solution.
