### ISSUE TITLE
Autoload doesn't seem to work, but apply works fine

### ISSUE THREAD

**Issue by letterlock** [sezanzeb/key-mapper#154]
Hello, first of all thank you for this program, it has been very nice to be able to keep using my razer tartarus.
Though writing keybinds to it manually by starting key-mapper and clicking apply seems to work, it doesn't seem to be doing anything on startup. I looked through the resolved issues, but I wasn't able to find anything conclusive, and unfortunately I'm not very savvy at any of this, so I hope you'll bear with my ignorance.
I've posted the logs below that you requested, and I rebuilt the program from source according to your installation instructions in the readme.md.

1. `key-mapper-control --version`
`key-mapper 1.0.0 c78d4d7e8e461dd2c29db8bd5979b4476848b5b7 https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0`

2. which linux distro (ubuntu 20.04, manjaro, etc.)
`Pop!_OS 21.04`

3. `echo $XDG_SESSION_TYPE`
`x11`

4. which desktop environment (gnome, plasma, xfce4, etc.)
`gnome`

5. `sudo ls -l /proc/1/exe`
`lrwxrwxrwx 1 root root 0 Jul 27 18:50 /proc/1/exe -> /usr/lib/systemd/systemd`

6. `cat ~/.config/key-mapper/config.json`
```
{
    "autoload": {
        "Razer Razer Tartarus V2": "tartarus"
    },
    "macros": {
        "keystroke_sleep_ms": 10
    },
    "gamepad": {
        "joystick": {
            "non_linearity": 4,
            "pointer_speed": 80,
            "left_purpose": "none",
            "right_purpose": "none",
            "x_scroll_speed": 2,
            "y_scroll_speed": 0.5
        }
    }
}
```

7. `key-mapper-control --command hello`
`Found "Razer Razer Tartarus V2"
Connected to the service
Daemon answered with "hello"`
8. `systemctl status key-mapper -n 50`
```
key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/lib/systemd/system/key-mapper.service; enabled; vendor preset: enabled)
     Active: activating (start) since Tue 2021-07-27 18:59:57 CEST; 51s ago
   Main PID: 856 (key-mapper-serv)
      Tasks: 1 (limit: 18931)
     Memory: 17.6M
     CGroup: /system.slice/key-mapper.service
             └─856 /usr/bin/python3 /usr/bin/key-mapper-service

Jul 27 18:59:57 pop-os systemd[1]: Starting Service to inject keycodes without the GUI application...
Jul 27 18:59:58 pop-os key-mapper-service[856]: Exception in thread Thread-1:
Jul 27 18:59:58 pop-os key-mapper-service[856]: Traceback (most recent call last):
Jul 27 18:59:58 pop-os key-mapper-service[856]:   File "/usr/lib/python3/dist-packages/evdev/device.py", line 126, in __init__
Jul 27 18:59:58 pop-os key-mapper-service[856]:     fd = os.open(dev, os.O_RDWR | os.O_NONBLOCK)
Jul 27 18:59:58 pop-os key-mapper-service[856]: OSError: [Errno 19] No such device: '/dev/input/event6'
Jul 27 18:59:58 pop-os key-mapper-service[856]: During handling of the above exception, another exception occurred:
Jul 27 18:59:58 pop-os key-mapper-service[856]: Traceback (most recent call last):
Jul 27 18:59:58 pop-os key-mapper-service[856]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Jul 27 18:59:58 pop-os key-mapper-service[856]:     self.run()
Jul 27 18:59:58 pop-os key-mapper-service[856]:   File "/usr/lib/python3/dist-packages/keymapper/groups.py", line 334, in run
Jul 27 18:59:58 pop-os key-mapper-service[856]:     device = evdev.InputDevice(path)
Jul 27 18:59:58 pop-os key-mapper-service[856]:   File "/usr/lib/python3/dist-packages/evdev/device.py", line 128, in __init__
Jul 27 18:59:58 pop-os key-mapper-service[856]:     fd = os.open(dev, os.O_RDONLY | os.O_NONBLOCK)
Jul 27 18:59:58 pop-os key-mapper-service[856]: OSError: [Errno 19] No such device: '/dev/input/event6'
```

9. `sudo pkill -f key-mapper-service && sudo key-mapper-service -d & sleep 2 && key-mapper-control --command autoload`, are your keys mapped now?
My keys are not mapped, here is the output:
```
[1] 6575

[1]+  Stopped                 sudo pkill -f key-mapper-service && sudo key-mapper-service -d
Found "Razer Razer Tartarus V2"
ERROR: Service not running? g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name keymapper.Control was not provided by any .service files (2)
```

10. (while the previous command is still running) `sudo evtest` and search for a device suffixed by "mapped". Select it, does it report any events? Share the output.
I cannot find a device suffixed by mapped. Here is the output:
```
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Power Button
/dev/input/event1:	Power Button
/dev/input/event2:	ckb1: Corsair Gaming SCIMITAR PRO RGB Mouse vKB
/dev/input/event3:	Razer Razer Tartarus V2
/dev/input/event4:	Razer Razer Tartarus V2
/dev/input/event5:	Razer Razer Tartarus V2
/dev/input/event6:	HDA NVidia HDMI/DP,pcm=3
/dev/input/event7:	HDA NVidia HDMI/DP,pcm=7
/dev/input/event8:	HDA NVidia HDMI/DP,pcm=9
/dev/input/event9:	HDA NVidia HDMI/DP,pcm=11
/dev/input/event10:	SteelSeries Arctis Pro Wireless Consumer Control
/dev/input/event11:	SteelSeries Arctis Pro Wireless
/dev/input/event12:	Eee PC WMI hotkeys
/dev/input/event13:	ckb1: Corsair Gaming SCIMITAR PRO RGB Mouse vM
/dev/input/event14:	HD-Audio Generic Front Mic
/dev/input/event15:	HDA NVidia HDMI/DP,pcm=8
/dev/input/event16:	HD-Audio Generic Rear Mic
/dev/input/event17:	HDA NVidia HDMI/DP,pcm=10
/dev/input/event18:	HD-Audio Generic Line
/dev/input/event19:	HDA NVidia HDMI/DP,pcm=12
/dev/input/event20:	HD-Audio Generic Line Out Front
/dev/input/event21:	HD-Audio Generic Line Out Surround
/dev/input/event22:	HD-Audio Generic Line Out CLFE
/dev/input/event23:	HD-Audio Generic Front Headphone
/dev/input/event24:	ckb2: Corsair Gaming K70 LUX RGB Keyboard vKB
/dev/input/event25:	ckb2: Corsair Gaming K70 LUX RGB Keyboard vM
Select the device event number [0-25]: ^X^X^C
```

**Comment by sezanzeb** [comment]
Thanks for using the issue template!

There seem to be three points that are odd:
- "/dev/input/event6" is not the Tartarus, it is some NVidia stuff
- "/dev/input/event6" cannot be opened, but it is there in the list
- "ERROR: Service not running?" after the command

I wonder if the device paths get mixed up a bit on your computer after the login for whatever reason.

Frist, after login, please run `key-mapper-control --command autoload` without pkill and that other stuff. Is it injecting now?

If that works, can you please try to modify `/etc/xdg/autostart/key-mapper-autoload.desktop` to look like:

```
[Desktop Entry]
Type=Application
Exec=bash -c "sleep 1 && key-mapper-control --command stop-all && key-mapper-control --command autoload"
Name=key-mapper-autoload
Icon=/usr/share/key-mapper/key-mapper.svg
Comment=Starts injecting all presets that are set to automatically load for the user
```

which would add a timeout of one second before attempting to autoload. If that doesn't help, lets increase it to 5 seconds and try again

**Comment by letterlock** [comment]
Sorry for the late reply!

I don't know what happened, but it has just seemingly miraculously started working... Did you push an update since the issue was opened? If not, are there any tests I can run to figure out what changed?

**Comment by sezanzeb** [comment]
I didn't push anything.

I don't know, did you install any other updates on your system? Does it work consistently each time the computer starts?

If it happens again and seems to only work randomly after all, then lets try it with `sleep 1` and see if it fixes the problem permanently. Please keep me updated in that case

**Comment by Hells-Mike** [comment]
Actually I have the same problem and I have tried the `sleep 1` solution, but still not working.

1. ```
    key-mapper 1.0.0 542054b8e63a97aa21268758db6ffe92bf13e4f6 https://github.com/sezanzeb/key-mapper`
    python-evdev 1.1.2
    ```
2. MX Linux 19.4
3. `x11`
4. plasma
5. `lrwxrwxrwx 1 root root 0 ago  3 23:10 /proc/1/exe -> /usr/sbin/init`
6. ```
    {
        "autoload": {
            "HID 1bcf:08a0": "Normal"
        },
        "macros": {
            "keystroke_sleep_ms": 10
        },
        "gamepad": {
            "joystick": {
                "non_linearity": 4,
                "pointer_speed": 80,
                "left_purpose": "none",
                "right_purpose": "none",
                "x_scroll_speed": 2,
                "y_scroll_speed": 0.5
            }
        }
    }
    ```
7. ```
    Connected to the service
    Daemon answered with "hello"
    ```
8. ```
    System has not been booted with systemd as init system (PID 1). Can't operate.
    Failed to connect to bus: Host is down
    ```
9. yes
10. ```
    Input driver version is 1.0.1
    Input device ID: bus 0x3 vendor 0x1 product 0x1 version 0x1
    Input device name: "key-mapper HID 1bcf:08a0 mapped"
    Supported events:
      Event type 0 (EV_SYN)
      Event type 1 (EV_KEY)
        Event code 29 (KEY_LEFTCTRL)
      Event type 21 (EV_FF)
    Properties:
    Testing ... (interrupt to exit)
    ```
    It stay just stucked here without any other output.

**Comment by sezanzeb** [comment]
@Hells-Mike key-mappers service is for systemd. For other init system you'll have to write your own startup script

**Comment by Hells-Mike** [comment]
Sorry for late answer, i didn't have the time to test out a sysv script yet, but for 10 you are right I was pressing no button.

**Comment by sezanzeb** [comment]
> it has just seemingly miraculously started working

I'll close it then, if it happens again feel free to reopen
