### ISSUE TITLE
key-mapper-control doesn't load presets

### ISSUE THREAD

**Issue by NoXPhasma** [sezanzeb/key-mapper#161]
Share some logs please:

1.
```
key-mapper 1.0.0 7a78dfcdcb70a49e17e02521fa656cb4514ba151 https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0
```

2. Arch Linux
3. X11
4. Cinnamon
5. `/usr/lib/systemd/systemd`

6. paste the affected preset .json file from ~/.config/key-mapper/presets
```
❯ cat ~/.config/key-mapper/presets/Razer\ Razer\ Basilisk\ V2/Splitgate.json
{
    "mapping": {
        "2,6,-1": "y",
        "2,6,1": "x"
    }
}
```

### issue
`key-mapper-control` won't load the preset, but it works fine with `key-mapper-gtk`. When I try to load a preset with `key-mapper-control`, it just doesn't do anything and no error is given. There is also no log output of anything happening in the system service.
```
❯ key-mapper-control -d --device "Razer Razer Basilisk V2" --preset Splitgate
312843 0.01158 DEBUG key-mapper-control:237: Call for "['/usr/bin/key-mapper-control', '-d', '--device', 'Razer Razer Basilisk V2', '--preset', 'Splitgate']"
```

**Comment by NoXPhasma** [comment]
I didn't realized that I've had to also use the `--command start` switch.

**Comment by cybermaus** [comment]
You may find `--command autoload` even easer then `--command start <name>`

**Comment by NoXPhasma** [comment]
Yes, but I want this profile only to be loaded when I start a specific game.
