### ISSUE TITLE
Hold-keystroke doesn't work with mouse click

### ISSUE THREAD

**Issue by tukkek** [sezanzeb/key-mapper#162]
`h(k(BTN_MOUSE))` doesn't work consistently with something like `h(k(a))`, or consistently with the documentation which states it will execute the action "while the key is pressed" - it will not continually click the mouse. To be honest, I don't care as much about the consistency as I do about being able to achieve a "spam clicks while the key is pressed" action, which I can't seem to achieve in the program right now.

If this isn't realistic to do with the current notation (`h(k(BTN_MOUSE))`, consider this a feature request for something similar but mouse-oriented (say, `spam(BTN_MOUSE,500))` with 500 being the interval). Ideally the behavior should be consistent between mouse and keyboard but I understand there being technical limitations - the feature itself is extremely useful though, [with entire programs existing just for that purpose](http://xautoclick.sourceforge.net/about.html) so a much more complete package should also have it, hopefully!

Thanks you so much to all involved in making this program - every other Linux option is needlessly complicated for end-users or flawed in some fundamental way (for anything outside their very specific intended use-cases). I look forward to using key-mapper as my go-to input tweaking app for here onward! Thanks again!

**Comment by tukkek** [comment]
Just for clarity's sake: in my eyes, `h(BTN_MOUSE)` *does work as intended* - which means to "hold the mouse button as long as the key is pressed". If a fix for `h(k(BTN_MOUSE))` is incoming, please make note not the change the semantics/effect of the case that is actually working as intended.

Also if I missed something or there is another way to achieve this let me know, I'm brand-new to the package but it seems to me that `h(BTN_MOUSE)` is fulfilling is semantic and pragmatic purpose while `h(k(BTN_MOUSE))` isn't (even as compared to the same function for keyboard keys, which do behave as you'd expect them to).

Thanks again!

**Comment by sezanzeb** [comment]
In `sudo evtest` you can observe the injections by key-mapper. `h(k(BTN_MOUSE))` also seems to behave like `h(BTN_MOUSE)` on my computer, but when looking into evtest you can see that it actually is injecting a lot of clicks. So the environment seems to do some magic there, probably because the events are injected so fast.

> say, spam(BTN_MOUSE,500)) with 500 being the interval

try `h(k(BTN_MOUSE).w(500))`

**Comment by sezanzeb** [comment]
feel free to reopen if there is still an issue
