### ISSUE TITLE
Can't launch: Namespace Gtk not available (needed to install libgtk-3-dev)

### ISSUE THREAD

**Issue by camsaul** [sezanzeb/key-mapper#170]
I installed the package via the `.deb` e.g.

```
# Fails because of missing dependencies
dpkg -i key-mapper-1.0.0.deb
# Install missing dependencies
apt-get install -f 
# Ok, now install the package
dpkg -i key-mapper-1.0.0.deb
```

However, it still doesn't work: 

```
$ key-mapper-gtk
Traceback (most recent call last):
  File "/usr/bin/key-mapper-gtk", line 30, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

I fixed this by installing `libgtk-3-dev`... shouldn't this have been a dependency for the package, so it would have been installed by `apt-get install -f`?

**Comment by sezanzeb** [comment]
Probably yes then. I guess most people already had in on their system. If you want you can make a pull request to add it to https://github.com/sezanzeb/key-mapper/blob/main/DEBIAN/control

**Comment by sezanzeb** [comment]
I just came back to this and tried it on my laptop. key-mapper starts there without libgtk-3-dev, but it has libgtk-3-0 installed, which is a dependency of libgtk-3-dev.

I'm adding libgtk-3-0 to the dependencies
