### ISSUE TITLE
Final Step fails on Install (enabling service error) 

### ISSUE THREAD

**Issue by LaurentOngaro** [sezanzeb/key-mapper#172]
I'm using Pop!Os 21.04 (Ubuntu 21.04 based) and the following error occurs when installing

`Failed to enable unit: Unit file key-mapper.service does not exist`

I occurs with both installation methods (debian package and python pip)

BTW , I managed to install without issue on my main machine (that is Arch Based) 

Thanks for this fantastic tools !! Very Very useful !

**Comment by sezanzeb** [comment]
please run

```
file /usr/lib/systemd/system/key-mapper.service
```

```
sudo systemctl daemon-reload
systemctl status key-mapper
```

**Comment by sezanzeb** [comment]
feel free to reopen if you have new information and if it still doesn't work

**Comment by LaurentOngaro** [comment]
sorry for the delay.
many thanks for the answer !
issue closed for me , finally I stay on Arch instead of Pop!Os, because I miss the AUR too much !

**Comment by FeFiFoFu** [comment]
Hi, I'm using Pop OS 21.04 and ran into the same issue.  I tried your Aug 24 suggestion.  Service failed:

`key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/lib/systemd/system/key-mapper.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-11-23 10:47:42 MST; 6min ago
   Main PID: 4869 (code=exited, status=1/FAILURE)

Nov 23 10:47:42 pop systemd[1]: Starting Service to inject keycodes without the GUI application...
Nov 23 10:47:42 pop key-mapper-service[4869]: Traceback (most recent call last):
Nov 23 10:47:42 pop key-mapper-service[4869]:   File "/usr/bin/key-mapper-service", line 28, in <module>
Nov 23 10:47:42 pop key-mapper-service[4869]:     from keymapper.logger import update_verbosity, log_info, \
Nov 23 10:47:42 pop key-mapper-service[4869]: ModuleNotFoundError: No module named 'keymapper'
Nov 23 10:47:42 pop systemd[1]: key-mapper.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 10:47:42 pop systemd[1]: key-mapper.service: Failed with result 'exit-code'.
Nov 23 10:47:42 pop systemd[1]: Failed to start Service to inject keycodes without the GUI application.
`

**Comment by sezanzeb** [comment]
> and ran into the same issue

I think this is a very different issue

Anyway, please post the logs from your installation attempt

**Comment by FeFiFoFu** [comment]
Here is installation attempt.

```
(base) fefifofu@pop:~/Downloads$ sudo apt install ./key-mapper-1.2.1.deb 
[sudo] password for fefifofu: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'key-mapper' instead of './key-mapper-1.2.1.deb'
key-mapper is already the newest version (1.2.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up key-mapper (1.2.1) ...
Job for key-mapper.service failed because the control process exited with error code.
See "systemctl status key-mapper.service" and "journalctl -xe" for details.
dpkg: error processing package key-mapper (--configure):
 installed key-mapper package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 key-mapper
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I ran "systemctl status" again and it's same as I posted.  I ran "journalctl -xe" and I didn't see anything related to key-mapper.  I also ran tried alternative install method from instructions provided (eg. git clone, build.sh) and ran into an error there too (eg. permission error for user _apt).

**Comment by sezanzeb** [comment]
Are you in a pipenv?

**Comment by sezanzeb** [comment]
Please try `python3 -c "import sys; print(sys.path)"`, and check where python packages are usually found. Example output:

```
['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/vs-mango/.local/lib/python3.9/site-packages', '/usr/lib/python3.9/site-packages', '/mnt/data/Code/key-mapper']
```

Then find out where key-mappers package got installed to, for example by running `find /usr -name keymapper`. For me it is in `/usr/lib/python3.9/site-packages/keymapper`, which also happens to be one of the paths of the previous command.

**Comment by FeFiFoFu** [comment]
I am using Conda.  I did find keymapper in my site-packages in a Conda env!

**Comment by sezanzeb** [comment]
You could try to leave the env and then install key-mapper again

**Comment by FeFiFoFu** [comment]
Yes it worked. `conda deactivate` then `sudo apt purge key-mapper` then reinstall. Works great.  It was removed from my conda env too.  Thanks for the help!  Ko-fi incoming!
