### ISSUE TITLE
Only works after first unlock

### ISSUE THREAD

**Issue by RisingOrange** [sezanzeb/key-mapper#18]
Thanks for making the app!

I have installed the deb package (version 0.6).
I am on pop-os 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu.

I have autoload enabled and it works, but only after I unlock the screen for the first time since a reboot. 
I want to be able to type a specific character that is part of my password while on the lockscreen.
Can I maybe just run a command to make the program start right after a reboot?
I tried adding
```@reboot sudo systemctl start key-mapper && sudo systemctl enable key-mapper```
to my crontab file but it didn't work.

Thanks for your help!

**Comment by sezanzeb** [comment]
systemctl controls the service that runs at all times and it receives commands as soon as the user logs in to load a specific config file. So on its own it won't start any injection.

You could try `sudo runuser -l your_user -c "key-mapper-control --command autoload"`. But it would be better if I added another parameter to key-mapper-control to autoload using a specific config file.

**Comment by sezanzeb** [comment]
Try `key-mapper-control --command autoload --config-dir "home/you/.config/key-mapper/"` with the newest git commit

replace `you` with your username

**Comment by RisingOrange** [comment]
Thanks for the quick reply!

I tried running
```sudo runuser -l your_user -c "key-mapper-control --command autoload```
on startup but it didn't work, the output was:

Loaded config from "/home/root/.config/key-mapper/config.json"
xmodmap:  unable to open display ''

I will just change my password then.

**Comment by RisingOrange** [comment]
Thanks, now it works perfectly!
