### ISSUE TITLE
Can't map broken keys

### ISSUE THREAD

**Issue by ShadowGoat128134** [sezanzeb/key-mapper#180]
Due to the way this accepts input, there's no way to map a shortcut to a broken key as far as I can tell, unless I'm being really dumb. I have a broken A key, but I can't remap I can't input "A" in the event listener thing. It also does not listen for inputs from external keys as far as I can tell.

**Comment by sezanzeb** [comment]
> inputs from external keys

what is that

> a broken A key

how is it broken? If your keyboard has a physical defect that prevents the A key from working, then no software will be able to fix it.

**Comment by ShadowGoat128134** [comment]
Sorry, bad wording. I mean the physical “A” key is broken, and the usual key combination I replace it with is “control+alt+s” but I can’t figure out how to be able to tell the software that I want it to output “A” when I do that, because to set the key that’s being mapped I need to be able to press the key, which I can’t, if that makes sense. It listens for key presses and doesn’t allow you to manually input what I want it to do, it seems like.

**Comment by sezanzeb** [comment]
but you can press A on your other keyboard, right?

![image](https://user-images.githubusercontent.com/28510156/132007962-8d29f949-6e2a-4a17-b4c1-a448e1105f22.png)

It doesn't matter which device you use to input the key in the right column

**Comment by ShadowGoat128134** [comment]
I’ve tried that mapping and it doesn’t seem to do anything.

**Comment by sezanzeb** [comment]
try `k(Control_L).k(Alt_L).h(a)`

**Comment by sezanzeb** [comment]
feel free to reopen and comment if you are still having issues
