### ISSUE TITLE
Space Cadet Shift

### ISSUE THREAD

**Issue by nan0tube** [sezanzeb/key-mapper#183]
Any idea if Space Cadet Shift <sup>[1](#fn1)</sup><sup>[2](#fn2)</sup> can be mapped/implemented?

<a name="fn1">1</a>: [Space Cadet Shift - QMK](https://beta.docs.qmk.fm/using-qmk/advanced-keycodes/feature_space_cadet)
<a name="fn2">2</a>: [A Modern Space Cadet / Steve Losh](https://stevelosh.com/blog/2012/10/a-modern-space-cadet/#s17-shift-parentheses)

**Comment by sezanzeb** [comment]
I think I just came up with a way to implement this. But I need some time to think about the best way to make this configurable. 

How would you name a macro function that
- does exactly what is described above, but configurable to write other keys than `(` and `)`
- works like `if the key is still the most recently pressed key then ... else ...`
- works like `if the key has been combined with any other key then ... else ...`
- works like `if this key has been combined with this keycode + value then ... else ...`

**Comment by nan0tube** [comment]
I just found out about key-mapper, so may not be able to come up with a name that is consistent with other parts of the project. Nevertheless here's my shot at it:
```
mod(mod_key, combined_key, <mod_key+combined_key event>, <mod_key+!combined_key event>, <mod_key only event>)
```

**Comment by sezanzeb** [comment]
what about

```
ifTab(a, b, 100)
# and even possibly at some point
ifDoubleTab(a, b, 100)
```
- if tabbed write a
- otherwise (if combined with another key or if too much time passes) b
- the number would be the timeframe in which the key has to be released in ms, 0 (default) to make it infinitely large

**Comment by nan0tube** [comment]
Perhaps you meant `if_tap`? In any case this looks way more elegant!

**Comment by sezanzeb** [comment]
yes, thanks. Ok

**Comment by sezanzeb** [comment]
I want to rewrite the architecture a little bit for this, it will take a little while. I'll let you know when there is something to try out

**Comment by sezanzeb** [comment]
Please try the https://github.com/sezanzeb/key-mapper/tree/if_tap branch

writing opening and closing brackets is a bit complicated if they are only accessible via modifiers. On my keyboard it would be:

`m(KEY_LEFTSHIFT, k(8))`

So for example this macro should write a "(" if the key is released within 1 second. If the key is combined with any other key or if you wait for too long it should write a shift

`if_tap(m(KEY_LEFTSHIFT, k(8)), k(KEY_LEFTSHIFT), 1000)`

**Comment by sezanzeb** [comment]
pushed some more changes, for me it just worked correctly

**Comment by sezanzeb** [comment]
I just realized that the if_tap functionality might not be quite fitting

Imagine someone is playing a game and continuously quickly hits button A,

button B is mapped with if_tap

if button A happens to be pressed while button B is pressed, if_tap will fail.

if button A happens to be pressed before button B is pressed, if_tap will work.

**Comment by sezanzeb** [comment]
pushed if_single

left shit -> `if_single(m(KEY_LEFTSHIFT, k(8)), h(KEY_LEFTSHIFT))`

**Comment by nan0tube** [comment]
Had trouble installing from the new branch. Referencing instructions in README.md for Ubuntu (20.04), here's what I did:

```
$ sudo apt purge key-mapper
$ sudo apt install git python3-setuptools gettext
$ git clone https://github.com/sezanzeb/key-mapper.git
$ git switch if_tap
$ cd key-mapper && ./scripts/build.sh
$ sudo apt install ./dist/key-mapper-1.0.0.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'key-mapper' instead of './dist/key-mapper-1.0.0.deb'
key-mapper is already the newest version (1.0.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up key-mapper (1.0.0) ...
Failed to enable unit: Unit file key-mapper.service does not exist.
Failed to start key-mapper.service: Unit key-mapper.service not found.
dpkg: error processing package key-mapper (--configure):
 installed key-mapper package post-installation script subprocess returned error exit status 5
Errors were encountered while processing:
 key-mapper
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Is there anything that I can try?

**Comment by sezanzeb** [comment]
> key-mapper is already the newest version (1.0.0).

sounds like typical package manager bs

try `sudo apt --reinstall install ./dist/key-mapper-1.0.0.deb`

**Comment by nan0tube** [comment]
Used `dpkg` to eliminate package manager interference (`sudo apt --reinstall install ./dist/key-mapper-1.0.0.deb` returned similar `dpkg` error):
```
$ sudo dpkg -i ./dist/key-mapper-1.0.0.deb
Selecting previously unselected package key-mapper.
(Reading database ... 260402 files and directories currently installed.)
Preparing to unpack ./dist/key-mapper-1.0.0.deb ...
Unpacking key-mapper (1.0.0) ...
Setting up key-mapper (1.0.0) ...
Job for key-mapper.service failed because the control process exited with error code.
See "systemctl status key-mapper.service" and "journalctl -xe" for details.
dpkg: error processing package key-mapper (--install):
 installed key-mapper package post-installation script subprocess returned error exit status 1
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 key-mapper
```

Found related error in systemd logs:
```
Sep 23 16:55:43 host key-mapper-service[3332345]: Found "USB Keyboard"
Sep 23 16:55:43 host key-mapper-service[3332345]: `xmodmap` command not found
Sep 23 16:55:43 host key-mapper-service[3332345]: Traceback (most recent call last):
Sep 23 16:55:43 host key-mapper-service[3332345]:   File "/usr/bin/key-mapper-service", line 48, in <module>
Sep 23 16:55:43 host key-mapper-service[3332345]:     from keymapper.daemon import Daemon
Sep 23 16:55:43 host key-mapper-service[3332345]:   File "/usr/lib/python3/dist-packages/keymapper/daemon.py", line 40, in <module>
Sep 23 16:55:43 host key-mapper-service[3332345]:     from keymapper.injection.injector import Injector, UNKNOWN
Sep 23 16:55:43 host key-mapper-service[3332345]:   File "/usr/lib/python3/dist-packages/keymapper/injection/injector.py", line 38, in <module>
Sep 23 16:55:43 host key-mapper-service[3332345]:     from keymapper.injection.consumer_control import ConsumerControl
Sep 23 16:55:43 host key-mapper-service[3332345]:   File "/usr/lib/python3/dist-packages/keymapper/injection/consumer_control.py", line 29, in <module>
Sep 23 16:55:43 host key-mapper-service[3332345]:     from keymapper.injection.consumers.event_producer import EventProducer
Sep 23 16:55:43 host key-mapper-service[3332345]: ModuleNotFoundError: No module named 'keymapper.injection.consumers'
```

`xmodmap` is present though.
```
$ xmodmap -version
xmodmap 1.0.9
```

Any thoughts?

**Comment by sezanzeb** [comment]
> Sep 23 16:55:43 host key-mapper-service[3332345]: `xmodmap` command not found

this is not critical, we can ignore that for now

> Sep 23 16:55:43 host key-mapper-service[3332345]: ModuleNotFoundError: No module named 'keymapper.injection.consumers'

I pushed a fix, it was because `packages` in setup.py didn't include 'keymapper.injection.consumers'

**Comment by nan0tube** [comment]
Installed successfully, thanks for the fix! As an initial assessment, seems to work as described!

Just sharing some `xev` output from qmk implementation for your consideration (my bad, should have shared earlier):
- When a Space Cadet Shift is pressed and released within a predefined time period (same as `key-mapper`)
```
KeyPress event, serial 31, synthetic NO, window 0xbe00001,
    root 0x2a0, subw 0x0, time 972341903, (67,2), root:(6471,731),
    state 0x10, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0xbe00001,
    root 0x2a0, subw 0x0, time 972341951, (67,2), root:(6471,731),
    state 0x11, keycode 18 (keysym 0x28, parenleft), same_screen YES,
    XKeysymToKeycode returns keycode: 187
    XLookupString gives 1 bytes: (28) "("
    XmbLookupString gives 1 bytes: (28) "("
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0xbe00001,
    root 0x2a0, subw 0x0, time 972341959, (67,2), root:(6471,731),
    state 0x11, keycode 18 (keysym 0x28, parenleft), same_screen YES,
    XKeysymToKeycode returns keycode: 187
    XLookupString gives 1 bytes: (28) "("
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0xbe00001,
    root 0x2a0, subw 0x0, time 972341967, (67,2), root:(6471,731),
    state 0x11, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

- When a Space Cadet Shift is pressed and released outside a predefined time period (different from `key-mapper` - only the corresponding shift event is fired)
```
KeyPress event, serial 46, synthetic NO, window 0xbe00001,
    root 0x2a0, subw 0x0, time 972263873, (154,81), root:(6558,810),
    state 0x10, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 46, synthetic NO, window 0xbe00001,
    root 0x2a0, subw 0x0, time 972266993, (154,81), root:(6558,810),
    state 0x11, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

Personally, not firing a parenthesis provides an option to "cancel" the action. If I held down shift in anticipation of entering a symbol, I can choose to "cancel" that decision by releasing the shift - which is also the original behaviour of shift.

Will continue to use it and update if there are new observations.

**Comment by nan0tube** [comment]
> shift+mouse combos will fail with this (like selecting text between the text-cursor and the click position), key-mapper was not designed to do those things cross-device. if_single on a keyboard won't be able to trigger when a mouse button is used.

Just encountered this (shift-click) during my normal use; would this be naturally solved if `key-mapper` is able to follow the qmk implementation mentioned above?

**Comment by sezanzeb** [comment]
> When a Space Cadet Shift is pressed and released outside a predefined time period (different from key-mapper - only the corresponding shift event is fired)

I'm confused

- shift down, shift release -> "(" written
- shift down, a down -> "A" written
- shift down, wait for some time, shift release -> what would happen in qmk?
- shift down, wait for some time, a down -> what would happen in qmk?

> Just encountered this (shift-click) during my normal use; would this be naturally solved if key-mapper is able to follow the qmk implementation mentioned above?

The problem is key-mappers architecture, I don't know right now how I can make that work. That would not be a trivial change

**Comment by sezanzeb** [comment]
I think the chances of making it work cross-device aren't that bad after all. But first I'll finish this without further changes to the architecture

**Comment by nan0tube** [comment]
The snippet that I was using:

```
    "1,42,1": "if_single(m(KEY_LEFTSHIFT, k(9)), h(KEY_LEFTSHIFT))",
    "1,54,1": "if_single(m(KEY_RIGHTSHIFT, k(0)), h(KEY_RIGHTSHIFT))"
```

> * shift down, shift release -> "(" written with qmk?

Yes

> * shift down, a down -> "A" written with qmk?

Yes

> * shift down, wait for some time, shift release -> what would happen in qmk?

Shift event. No visible character.

> * shift down, wait for some time, a down -> what would happen in qmk?

"A"

**Comment by sezanzeb** [comment]
ah, so that needs a combination of if_single and if_tap

the following options potentially exist to implement it:

#### 1. adding a macro to run two macros in parallel

would work thanks to asyncio

```py
parallel(
  if_single(, set(shift, 1))),
  if_tap(, set(shift, 1)), 500)
).ifeq(
  shift,
  1,
  h(KEY_LEFTSHIFT),
  m(KEY_LEFTSHIFT, k(9))
)
```

#### 2. adding a macro function that does both

```py
space_cadet(m(KEY_LEFTSHIFT, k(9)), h(KEY_LEFTSHIFT), 500)
```

#### 3. adding a timeout parameter to if_single

not so sure about this one, decisions to add parameters to functions can't be reverted
so if there is a clearer way to solve it (by adding a new function or something) I'll always
favor that.

```py
if_single(m(KEY_LEFTSHIFT, k(9)), h(KEY_LEFTSHIFT), 500)
```

#### 4. adding a special time variable and if_lt

```py
if_single(
  if_lt(time, 500, m(KEY_LEFTSHIFT, k(9)), h(KEY_LEFTSHIFT)),
  h(KEY_LEFTSHIFT)
)
```

#### 5. adding a funky if function

requires support for arrays

```py
if_and(
  [[tap, 500], [single]]
  m(KEY_LEFTSHIFT, k(9)),
  h(KEY_LEFTSHIFT)
)
```

Please sort them by how much you would like them, and if you think there is something

**Comment by sezanzeb** [comment]
I wonder if `set(a, 1).if_eq(a, 1, x(), y())` should use a `*` to get the value of a variable `set(a, 1).if_eq(*a, 1, x(), y())`, because it would allow `set(a, 1).set(b, 1).if_eq(*a, *b, x(), y())`

`ifeq` could use the old functionality and remain there for compatibility with old macros.

**Comment by nan0tube** [comment]
Wow so many options! I would go for option 3 for its simplicity.

**Comment by sezanzeb** [comment]
update:

`if_single` is released, as well as a lot of other architecture changes, refactorings and new macro syntax features. I'll work on adding the timeout parameter to `if_single` soon, probably at some point this weekend but no guarantee.

**Comment by sezanzeb** [comment]
if_single supports `timeout=1000` now, the number is in milliseconds.

**Comment by nan0tube** [comment]
Have been using main branch for a day now, works great so far!

**Comment by nan0tube** [comment]
Just updated to 1.2.0 and it is working well so far. I am effectively using https://github.com/sezanzeb/key-mapper/issues/183#issuecomment-932818383 and shift-click works too.

Since the issue is now implemented, I'll close the issue. Thank you for the feature 🙏
