### ISSUE TITLE
App doesn't open on ZOrin OS

### ISSUE THREAD

**Issue by Pretuer** [sezanzeb/key-mapper#19]
it seems like I need a password to open the app no 1. my OS is also not recognising it's install  no 2 it's not opening

**Comment by sezanzeb** [comment]
yes, the application indeed needs a password because it needs to read your devices input.

What do you mean with "not recognising it's install"?

Can you open a terminal, type `key-mapper-gtk-pkexec` and post the output here please?

**Comment by sezanzeb** [comment]
please try the following:

```
sudo apt install git python3-setuptools
git clone https://github.com/sezanzeb/key-mapper.git
cd key-mapper && ./scripts/build.sh
sudo dpkg -i ./dist/key-mapper-0.6.0.deb
sudo apt -f install  # installs dependencies
```

I just tried it in a vm and it works with the recent change
