### ISSUE TITLE
some mappings not available

### ISSUE THREAD

**Issue by figadore** [sezanzeb/key-mapper#195]
1. `key-mapper-control --version`

key-mapper 1.2.1 2803bb841e19232ec08c57bdfca66d0535131dab https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0

2. If a button on your device doesn't show up in the GUI, verify that the button is reporting an event via `sudo evtest`. If not, key-mapper won't be able to map that button.

evtest shows raw key inputs

3. If yes, please run `key-mapper-gtk -d`, reproduce the problem and then share the logs.

[key-mapper.log](https://github.com/sezanzeb/key-mapper/files/7385095/key-mapper.log)

I'm using `/dev/input/event4`, which I think is my laptop's built-in keyboard. I cannot create certain mappings, while I can create others. For example, if I want to map `3` to `<` and `4` to `>`, the mapping `less` shows up and autocompletes and maps correctly, but `greater` is not an option. When I type "greater" manually, even though it doesn't autocomplete, the mapping does nothing. Similar issue for other symbols, such as `dollar` (`KEY_DOLLAR` does show up, but doesn't seem to do anything) and `braceleft`, `braceright`, etc.

Sorry if this is a duplicate, I looked through the issues and couldn't find anything relevant

**Comment by sezanzeb** [comment]
If you don't mind tinkering with xmodmap and are on X11, then this might work as well without having to use `Shift_L`: https://github.com/sezanzeb/key-mapper/blob/clean-history-main/readme/examples.md#emitting-unavailable-symbols

**Comment by sezanzeb** [comment]
There might be ways to improve that situation. One Idea was to show a tool to find key combinations based on a symbol: https://github.com/sezanzeb/key-mapper/issues/90. But since strings are supported now in the macro syntax, a function like `special_character(">")` might be implementable, which looks up `xmodmap` to find the correct combination that results in this symbol.
