### ISSUE TITLE
Buttons suddenly unrecognized

### ISSUE THREAD

**Issue by laserburn** [sezanzeb/key-mapper#199]
Been using Key Mapper for a while to duplicate the left and middle click to another to unused buttons on the trackball, it's really handy to rotate the finger usage and reduce the pain. 
Screenshot of the settings:
https://paste.pics/6538fc72a77b677202bd0c850d98a774

But suddenly, the new middle click is not working any more. I tried to assign it again, but Key Mapper appears not to get input from that button any more. So I try the next button, again, it doesn't react when I try to map it, like I'm not even pressing it. Funny enough, the button that was mapped as left click is still working.

nikola@Kassad:~$ sudo key-mapper-gtk -d
[sudo] password for nikola: 
Loaded config from "/home/nikola/.config/key-mapper/config.json"
Writing "/home/nikola/.config/key-mapper/xmodmap.json"
0.06180 INFO: logger.py, line 140, key-mapper 0.6.0
0.06211 INFO: logger.py, line 143, python-evdev 1.3.0
0.06215 WARNING: logger.py, line 149, Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
0.06222 DEBUG: logger.py, line 155, pid 66030
0.09354 DEBUG: data.py, line 85, Found data at "/usr/share/key-mapper"
0.21852 DEBUG: getdevices.py, line 100, Discovering device paths
0.22046 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 0001, product 0001, version 0001", "/dev/input/event21", "key-mapper ELECOM ELECOM TrackBall Mouse"
0.22063 SPAM: getdevices.py, line 126, Found "bus: 0019, vendor 0000, product 0000, version 0000", "/dev/input/event8", "Eee PC WMI hotkeys"
0.22081 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 056e, product 00fe, version 0111", "/dev/input/event7", "ELECOM ELECOM TrackBall Mouse"
0.22091 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 258a, product 0016, version 0110", "/dev/input/event6", "BY Tech Usb Gaming Keyboard Mouse"
0.22105 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 258a, product 0016, version 0110", "/dev/input/event5", "BY Tech Usb Gaming Keyboard"
0.22121 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 258a, product 0016, version 0110", "/dev/input/event4", "BY Tech Usb Gaming Keyboard Consumer Control"
0.22130 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 258a, product 0016, version 0110", "/dev/input/event3", "BY Tech Usb Gaming Keyboard System Control"
0.22146 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 258a, product 0016, version 0110", "/dev/input/event2", "BY Tech Usb Gaming Keyboard"
0.22185 INFO: getdevices.py, line 189, Found "key-mapper ELECOM ELECOM TrackBall Mouse", "Eee PC WMI hotkeys", "ELECOM ELECOM TrackBall Mouse", "BY Tech Usb Gaming Keyboard"
0.22328 DEBUG: presets.py, line 144, The newest preset is "ELECOM ELECOM TrackBall Mouse", "new preset"
0.22356 DEBUG: window.py, line 535, Selecting device "ELECOM ELECOM TrackBall Mouse"
0.22466 DEBUG: window.py, line 302, "ELECOM ELECOM TrackBall Mouse" presets: "new preset"
0.22563 DEBUG: window.py, line 624, Selecting preset "new preset"
0.22576 INFO: mapping.py, line 162, Loading preset from "/home/nikola/.config/key-mapper/presets/ELECOM ELECOM TrackBall Mouse/new preset.json"
0.22608 SPAM: mapping.py, line 195, Key((1, 278, 1),) maps to BTN_MIDDLE
0.22621 SPAM: mapping.py, line 195, Key((1, 277, 1),) maps to BTN_LEFT
0.23948 INFO: window.py, line 589, Device "ELECOM ELECOM TrackBall Mouse" is currently mapped
0.29606 DEBUG: reader.py, line 145, Starting reading keycodes from "ELECOM ELECOM TrackBall Mouse"
68.8190 INFO: window.py, line 334, Cannot change keycodes while injecting

**Comment by laserburn** [comment]
After playing a bit with xev, it appears that there is a button or electrical problem with my trackball, it would register presses when I press towards inside, but not towards outside, like I normally do. But after I press some other buttons, it sort of wakes up and accepts presses towards outside as well, so it could be electrical, not just button. Already breaking after less than two years.

Still, something appears wrong with Key Mapper. After I click on the button to add new mapping, it doesn't recognize my button presses on mouse or keyboard. If I remember correctly, that's how you use it.

**Comment by sezanzeb** [comment]
> 68.8190 INFO: window.py, line 334, Cannot change keycodes while injecting

Did you hit the "Restore Defaults" button on the top right before editing your mapping?

**Comment by laserburn** [comment]
No. Is that some sort of limitation that you can't edit the active preset? I didn't see it mentioned somewhere.

**Comment by sezanzeb** [comment]
On the bottom left it should say

![image](https://user-images.githubusercontent.com/28510156/139559457-1973c5db-db2e-4b2c-8554-9bda0fed7ae2.png)

> Is that some sort of limitation

I think there would be ways around that issue, but it requires architecture changes. At the moment it is not possible to change the mapping as long as an injection is active
