### ISSUE TITLE
Auto Profile option

### ISSUE THREAD

**Issue by mobedoor** [sezanzeb/key-mapper#203]
Hello.
Autoprofile on window change would be a very useful feature. 
Thanks.

**Comment by sezanzeb** [comment]
Not possible: https://github.com/sezanzeb/key-mapper/discussions/20

**Comment by jose1711** [comment]
I think it's more accurate to say: impossible on Wayland, but definitely possible with Xorg. I put the following script together and it seems to work (turning injection on and off based on the current window). Uses `xdotool` and `qdbus`. Sadly there does not seem to be a way to find out which profile is currently loaded.

```
#!/bin/bash
device="Some device"
preset="Some preset"
window="Mozilla Firefox$"
echo "Set config dir.."
qdbus --system keymapper.Control /keymapper/Control keymapper.Control.set_config_dir $HOME/.config/key-mapper

function is_injected {
  # return 0 if injection for device ($1) is active, 1 otherwise
  device="$1"
  qdbus --system keymapper.Control /keymapper/Control keymapper.Control.get_state "${device}" | grep -q 4
  return $?
}


while :
do
  if xdotool getwindowfocus getwindowname | grep -q "${window}"
  then
    # check status of injection
    qdbus --system keymapper.Control /keymapper/Control keymapper.Control.get_state "${device}" | grep -q 4
    if ! is_injected "${device}"
    then
      echo "Starting injection ($window window is active).."
      qdbus --system keymapper.Control /keymapper/Control keymapper.Control.start_injecting "${device}" "${preset}"
    fi
  else
    if is_injected "${device}"
    then
      echo "Stopping injection.."
      qdbus --system keymapper.Control /keymapper/Control keymapper.Control.stop_injecting "${device}"
    fi
  fi
  sleep 5
done

```

If @sezanzeb agrees we may improve it and add to documentation as an example?

**Comment by sezanzeb** [comment]
> Sadly there does not seem to be a way to find out which profile is currently loaded.

This can be added and requires pulling a wire through:

1. key-mapper-command sends message via dbus
2. injector dbus receives
3. injector sends message over pipe
4. injection process receives message via pipe
5. injection process sends answer, and it goes back the same way

afterward key-mapper-control prints the message.

**Comment by sezanzeb** [comment]
> If @sezanzeb agrees we may improve it and add to documentation as an example?

yes, we can do that. We can add the code to the examples section. https://github.com/sezanzeb/key-mapper/blob/main/readme/examples.md. Maybe we can even add that as a file in the /readme folder, but I'd not add the file anywhere else to keep the philosophy of offering all features independently of the environment alive (even the usage of xmodmap might already be quite questionable therefore)
