### ISSUE TITLE
Python Install: No Module evdev

### ISSUE THREAD

**Issue by och4** [sezanzeb/key-mapper#204]
Pip install failed, but went with python3 install instead, but it's failing to load.

Running key-mapper, systemctl, and pipe install, & python reinstall
https://pastebin.com/MXhnvdMm

Fresh Install of Fedora 34 + i3

**Comment by sezanzeb** [comment]
`sudo pip install evdev`

**Comment by och4** [comment]
Sorry, I meant to update my post to include that python-evdev solved, but it wasn't included in the readme though?

**Comment by sezanzeb** [comment]
Dependencies should usually be installed automatically via https://github.com/sezanzeb/key-mapper/blob/main/setup.py#L125

I'm certain that the arch, pip and .deb installations will install dependencies, but not sure about `python3 setup.py install`. I'm not sure what the smartest way would be to get all dependencies installed if `pip` fails

**Comment by sezanzeb** [comment]
The proper long term solution would be if someone contributes a script to properly pack key-mapper for fedora
