### ISSUE TITLE
Logitech MX master 2S - Secound scroll wheel is not showing up independent

### ISSUE THREAD

**Issue by Darudas** [sezanzeb/key-mapper#206]
I am on the newest verion and I tryed sudo evtest and it showed both wheel as the same but solaar can also different between them so is there a way to get the volume just on my thumb wheel and not on my scroll wheel?

**Comment by sezanzeb** [comment]
If evtest reports the same events for both there is nothing key-mapper can do unfortunately

**Comment by sezanzeb** [comment]
You might have luck with https://github.com/libratbag/piper/, Logitech MX master 2S seems to be supported

**Comment by Darudas** [comment]
I also tryed piper but unfortually they also do not have the secound scroll wheel as an option to set and sadly logi options also does not store settings on the device itself.

**Comment by sezanzeb** [comment]
I'll close this then, sorry
