### ISSUE TITLE
key mapper not start

### ISSUE THREAD

**Issue by vadim212112** [sezanzeb/key-mapper#211]
after entering the password, the program window does not appear and programm is not start, if you run it in the terminal, the following error appears

(key-mapper-gtk:27083): Gtk-WARNING **: 09:37:49.214: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(key-mapper-gtk:27083): Gtk-WARNING **: 09:37:49.214: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(key-mapper-gtk:27083): Gtk-WARNING **: 09:37:49.214: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
key-mapper-gtk 1.2.1 70bc804f15c3539c87add5dff7a2082b7358396e https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0
Loaded config from "/home/vadim/.config/key-mapper/config.json"
Connected to the service
Traceback (most recent call last):
  File "/usr/bin/key-mapper-control", line 30, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
ERROR: Failed to pkexec the helper, code 256

manjaro kde 21.2 stable
i downgrade key-mapper to 1.2.1r14 from 1.2.1r16 & r15 and program work good

**Comment by sezanzeb** [comment]
Hey, thanks for reporting it. psutil is not required anymore now
