### ISSUE TITLE
Autoloading not working on sway

### ISSUE THREAD

**Issue by chorriwuarri** [sezanzeb/key-mapper#212]
1. `key-mapper-control --version`
key-mapper 1.2.1 f9e7ef1445ad649cd5de066f7718ca365a700c88 https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0

2. which linux distro (ubuntu 20.04, manjaro, etc.)
arch

3. `echo $XDG_SESSION_TYPE`
4. which desktop environment (gnome, plasma, xfce4, etc.) 
Sway

5. `sudo ls -l /proc/1/exe`
lrwxrwxrwx 1 root root 0 nov 25 21:55 /proc/1/exe -> /usr/lib/systemd/systemd

6. `cat ~/.config/key-mapper/config.json`
{
    "autoload": {
        "Logitech Gaming Mouse G502": "new preset",
        "Corsair Corsair Gaming K63 Keyboard": "mouse"
    },
    "macros": {
        "keystroke_sleep_ms": 10
    },
    "gamepad": {
        "joystick": {
            "non_linearity": 4,
            "pointer_speed": 80,
            "left_purpose": "none",
            "right_purpose": "none",
            "x_scroll_speed": 2,
            "y_scroll_speed": 0.5
        }
    }

7. `key-mapper-control --command hello`
ERROR: Service not running? g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name keymapper.Control was not provided by any .service files (2)

8. `systemctl status key-mapper -n 50`
key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendo>
     Active: failed (Result: timeout) since Thu 2021-11-25 21:55:47 CET; 5min a>
    Process: 630 ExecStartPre=/bin/sleep 15 (code=killed, signal=TERM)
        CPU: 774us

9. `sudo pkill -f key-mapper-service && sudo key-mapper-service -d & sleep 2 && key-mapper-control --command autoload`, are your keys mapped now?
[1] 2303

[1]+  Detenido                sudo pkill -f key-mapper-service && sudo key-mapper-service -d
ERROR: Service not running? g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name keymapper.Control was not provided by any .service files (2)

10. (while the previous command is still running) `sudo evtest` and search for a device suffixed by "mapped". Select it, does it report any events? Share the output.

key-mapper-control --command hello
ERROR: Service not running? g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name keymapper.Control was not provided by any .service files (2)

 systemctl status key-mapper.service 
× key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: failed (Result: timeout) since Thu 2021-11-25 21:55:47 CET; 12min ago
        CPU: 774us

nov 25 21:55:47 arch systemd[1]: Failed to start Service to inject keycodes without the GUI application.

I'm confused because in gnome it does work

it's probably a mistake on my part when configuring sway, but I can't resolve it.

if I run key mapper gtk, and press the apply button, it works correctly, but I have to do it on every restart.

**Comment by sezanzeb** [comment]
What does running `sudo key-mapper-service -d` print?

**Comment by chorriwuarri** [comment]
3092 0.21723 DEBUG groups.py:335: Discovering device paths
3092 0.23150 SPAM groups.py:367: Found "3_1133_49738_usb-0000:02:00.0-1", "/dev/input/event10", "Logitech Gaming Mouse G600 Keyboard", type: keyboard
3092 0.23232 SPAM groups.py:367: Found "3_1133_49738_usb-0000:02:00.0-1", "/dev/input/event9", "Logitech Gaming Mouse G600", type: mouse
3092 0.23455 SPAM groups.py:367: Found "3_6940_6976_usb-0000:00:14.0-7", "/dev/input/event6", "Corsair Corsair Gaming K63 Keyboard", type: keyboard
3092 0.23579 SPAM groups.py:367: Found "3_1133_49970_usb-0000:00:14.0-6", "/dev/input/event5", "Logitech Gaming Mouse G502 Keyboard", type: keyboard
3092 0.23660 SPAM groups.py:367: Found "3_1133_49970_usb-0000:00:14.0-6", "/dev/input/event4", "Logitech Gaming Mouse G502", type: mouse
3092 0.23730 SPAM groups.py:367: Found "25_0_6_LNXVIDEO", "/dev/input/event3", "Video Bus", type: unknown
3092 0.23894 SPAM groups.py:367: Found "25_0_3_PNP0C0E", "/dev/input/event0", "Sleep Button", type: unknown
3092 0.24019 INFO groups.py:438: Found "Logitech Gaming Mouse G600", "Corsair Corsair Gaming K63 Keyboard", "Logitech Gaming Mouse G502", "Video Bus", "Sleep Button"
3092 0.24671 DEBUG system_mapping.py:64: Gathering available keycodes
3092 0.25573 INFO system_mapping.py:78: Optional `xmodmap` command not found. This is not critical.
3092 0.25673 DEBUG system_mapping.py:86: Writing "/home/deivi/.config/key-mapper/xmodmap.json"
3092 0.26384 SPAM shared_dict.py:58: Starting SharedDict process
3126 0.27040 SPAM shared_dict.py:64: SharedDict process started
3092 0.27633 INFO logger.py:203: This output is also stored in "/var/log/key-mapper"
3092 0.27781 INFO logger.py:219: Logging to "/var/log/key-mapper"
3092 0.27803 INFO logger.py:163: key-mapper-service 1.2.1 f9e7ef1445ad649cd5de066f7718ca365a700c88 https://github.com/sezanzeb/key-mapper
3092 0.27837 INFO logger.py:168: python-evdev 1.4.0
3092 0.27861 WARNING logger.py:171: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
3092 0.27912 DEBUG daemon.py:148: Creating daemon
3092 0.27976 INFO config.py:248: Loaded config from "/home/deivi/.config/key-mapper/config.json"
3092 0.29543 DEBUG daemon.py:229: Running daemon

**Comment by sezanzeb** [comment]
Ok great, looks fine.

Now while this is running, open another terminal and use `key-mapper-control --command autoload`. Is your device mapped now?

**Comment by chorriwuarri** [comment]
> Ahora, mientras esto se está ejecutando, abra otra terminal y use `key-mapper-control --command autoload -d`. ¿Su dispositivo está mapeado ahora?
> 
> También en el paso 8, parece que faltan muchas cosas. 
it is possible that it is my fault when configuring sway, in gnome key-mapper works very well.
> Adjunte todos los`systemctl status key-mapper -n 50`

**Comment by chorriwuarri** [comment]
> Also in step 8, it looks like there is a lot of stuff missing.
it is possible that it is my fault when configuring sway, in gnome key-mapper works very well.

> Please attach all of `systemctl status key-mapper -n 50`
systemctl status key-mapper -n 50
× key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: failed (Result: timeout) since Fri 2021-11-26 10:08:26 CET; 9min ago
    Process: 555 ExecStartPre=/bin/sleep 15 (code=killed, signal=TERM)
        CPU: 790us

nov 26 10:08:26 arch systemd[1]: Failed to start Service to inject keycodes without the GUI application.

 > Now while this is running, open another terminal and use `key-mapper-control --command autoload -d`. Is your device mapped now?
yes it works

**Comment by sezanzeb** [comment]
For me, the systemctl status command looks like this:

```
● key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2021-11-26 09:19:09 CET; 1h 7min ago
   Main PID: 599 (key-mapper-serv)
      Tasks: 6 (limit: 19117)
     Memory: 45.3M
        CPU: 21.012s
     CGroup: /system.slice/key-mapper.service
             ├─  599 /usr/bin/python3 /usr/bin/key-mapper-service
             ├─ 1030 /usr/bin/python3 /usr/bin/key-mapper-service
             └─31402 /usr/bin/python3 /usr/bin/key-mapper-service

Nov 26 09:19:07 proxima systemd[1]: Starting Service to inject keycodes without the GUI application...
Nov 26 09:19:09 proxima key-mapper-service[599]: Starting logging to "/var/log/key-mapper"
Nov 26 09:19:09 proxima key-mapper-service[599]: key-mapper-service 1.2.1 70bc804f15c3539c87add5dff7a2082b7358396e https://github.com/sezanzeb/key-mapper
Nov 26 09:19:09 proxima key-mapper-service[599]: python-evdev 1.4.0
Nov 26 09:19:09 proxima systemd[1]: Started Service to inject keycodes without the GUI application.
Nov 26 09:19:18 proxima key-mapper-service[599]: Loaded config from "/home/mango/.config/key-mapper/config.json"
Nov 26 09:19:18 proxima key-mapper-service[599]: Loaded config from "/home/mango/.config/key-mapper/config.json"
Nov 26 09:19:18 proxima key-mapper-service[599]: Stopping all injections
Nov 26 09:19:18 proxima key-mapper-service[599]: Loaded config from "/home/mango/.config/key-mapper/config.json"
Nov 26 09:19:18 proxima key-mapper-service[599]: Loaded config from "/home/mango/.config/key-mapper/config.json"
Nov 26 09:19:18 proxima key-mapper-service[599]: Autoloading for all devices
Nov 26 09:19:19 proxima key-mapper-service[599]: Found "Razer Razer Naga Trinity", "Logitech USB Keyboard"
Nov 26 09:19:19 proxima key-mapper-service[599]: Autoloading for "Razer Razer Naga Trinity"
Nov 26 09:19:19 proxima key-mapper-service[599]: Loading preset from "/home/mango/.config/key-mapper/presets/Razer Razer Naga Trinity/GW2.json"
Nov 26 09:19:19 proxima key-mapper-service[599]: Optional `xmodmap` command not found. This is not critical.
Nov 26 09:19:19 proxima key-mapper-service[4629]: Starting injecting the mapping for "Razer Razer Naga Trinity"
Nov 26 09:19:19 proxima key-mapper-service[599]: Found "key-mapper Razer Razer Naga Trinity mapped", "Razer Razer Naga Trinity", "Logitech USB Keyboard"
Nov 26 09:19:19 proxima key-mapper-service[599]: Found "key-mapper Razer Razer Naga Trinity mapped", "Razer Razer Naga Trinity", "Logitech USB Keyboard"
Nov 26 09:19:19 proxima key-mapper-service[599]: Found "key-mapper Razer Razer Naga Trinity mapped", "Razer Razer Naga Trinity", "Logitech USB Keyboard"
Nov 26 09:19:19 proxima key-mapper-service[4629]: WARNING: Failed to get ABS info of "device /dev/input/event7, name "Razer Razer Naga Trinity", phys "usb-0000:28:00.3-4.3/input1"" for ke>
Nov 26 09:37:29 proxima key-mapper-service[599]: Loaded config from "/home/vs-mango/.config/key-mapper/config.json"
Nov 26 09:37:29 proxima key-mapper-service[599]: Loaded config from "/home/vs-mango/.config/key-mapper/config.json"
Nov 26 09:37:29 proxima key-mapper-service[599]: Stopping all injections
Nov 26 09:37:29 proxima key-mapper-service[599]: Stopping injecting keycodes for group "Razer Razer Naga Trinity"
Nov 26 09:37:29 proxima key-mapper-service[599]: Loaded config from "/home/vs-mango/.config/key-mapper/config.json"
Nov 26 09:37:29 proxima key-mapper-service[599]: Loaded config from "/home/vs-mango/.config/key-mapper/config.json"
Nov 26 09:37:29 proxima key-mapper-service[599]: Autoloading for all devices
Nov 26 09:37:30 proxima key-mapper-service[599]: Found "key-mapper Razer Razer Naga Trinity mapped", "Razer Razer Naga Trinity", "Logitech USB Keyboard"
Nov 26 09:37:30 proxima key-mapper-service[599]: Autoloading for "Razer Razer Naga Trinity"
Nov 26 09:37:30 proxima key-mapper-service[599]: Loading preset from "/home/vs-mango/.config/key-mapper/presets/Razer Razer Naga Trinity/Programming.json"
Nov 26 09:37:30 proxima key-mapper-service[599]: Stopping injecting keycodes for group "Razer Razer Naga Trinity"
Nov 26 09:37:30 proxima key-mapper-service[31402]: Starting injecting the mapping for "Razer Razer Naga Trinity"
Nov 26 09:37:30 proxima key-mapper-service[31402]: ERROR: Don't know what "KEY" is
Nov 26 09:37:30 proxima key-mapper-service[599]: Found "key-mapper Razer Razer Naga Trinity mapped", "Razer Razer Naga Trinity", "Logitech USB Keyboard"
Nov 26 09:37:30 proxima key-mapper-service[599]: Found "key-mapper Razer Razer Naga Trinity mapped", "Razer Razer Naga Trinity", "Logitech USB Keyboard"
Nov 26 09:37:30 proxima key-mapper-service[31402]: WARNING: Failed to get ABS info of "device /dev/input/event7, name "Razer Razer Naga Trinity", phys "usb-0000:28:00.3-4.3/input1"" for k>
```

I was expecting to see some log there

key-mapper should be completely independent of the compositor

**Comment by chorriwuarri** [comment]
I don't know if it will help, if I start key mapper gtk, it works fine until I restart the pc, but it still works if I restart sway.

key-mapper-gtk 
key-mapper-gtk 1.2.1 f9e7ef1445ad649cd5de066f7718ca365a700c88 https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0
Loaded config from "/home/deivi/.config/key-mapper/config.json"
Connected to the service
Found "key-mapper Corsair Corsair Gaming K63 Keyboard mapped", "Logitech Gaming Mouse G600", "Corsair Corsair Gaming K63 Keyboard", "Logitech Gaming Mouse G502", "Video Bus", "Sleep Button"
Loading preset from "/home/deivi/.config/key-mapper/presets/Sleep Button/new preset.json"

**Comment by sezanzeb** [comment]
> but it still works if I restart sway.

This is because key-mapper-service doesn't care about gnome/x11/wayland/sway/kde/etc. It even works within ttys.

> if I start key mapper gtk, it works fine

because the gui starts the service if it isn't running already

---

`Process: 555 ExecStartPre=/bin/sleep 15 (code=killed, signal=TERM)`

I wonder where that comes from

**Comment by sezanzeb** [comment]
please post `cat /usr/lib/systemd/system/key-mapper.service`

**Comment by chorriwuarri** [comment]
cat /usr/lib/systemd/system/key-mapper.service
[Unit]
Description=Service to inject keycodes without the GUI application

[Service]
Type=dbus
BusName=keymapper.Control
ExecStart=/usr/bin/key-mapper-service

[Install]
WantedBy=default.target
Alias=key-mapper.service

**Comment by chorriwuarri** [comment]
> ExecStartPre=/bin/sleep 15

oh I forced it for testing

**Comment by sezanzeb** [comment]
Are you able to find something about the service in `journalctl`?

**Comment by chorriwuarri** [comment]
> Are you able to find something about the services failure in `journalctl`?
 Failed to start Service to inject keycodes without the GUI application.

> How do you force that?

I edit the service, but it is already default.
I added this
ExecStartPre=/bin/sleep 15

in windows forcing delay fixes a lot of problems, I thought it might work.

**Comment by chorriwuarri** [comment]
in sway it is disabled to run applications with sudo, can the problem be there?
sudo key-mapper-gtk 
[sudo] password for deivi: 
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified

(key-mapper-gtk:8986): Gtk-WARNING **: 12:37:54.453: cannot open display: :1

**Comment by sezanzeb** [comment]
no, systemd runs before sway. If systemd wasn't able to run applications as root your operating system wouldn't be able to boot. key-mapper-service is usually started by systemd, it has nothing to do with sway

**Comment by sezanzeb** [comment]
you don't need to run key-mapper-gtk as root. It is specifically designed to use pkexec and a helper daemon in the background so that all environments support it.

**Comment by sezanzeb** [comment]
What happens if you run `sudo systemctl start key-mapper`?

**Comment by chorriwuarri** [comment]
I have added to my .bashrc file this
export XAUTHORITY=~/.Xauthority
and now systemd loads the service

● key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2021-11-26 14:06:03 CET; 3min 57s ago
   Main PID: 635 (key-mapper-serv)
      Tasks: 4 (limit: 38215)
     Memory: 50.4M
        CPU: 834ms
     CGroup: /system.slice/key-mapper.service
             ├─635 /usr/bin/python3 /usr/bin/key-mapper-service
             └─851 /usr/bin/python3 /usr/bin/key-mapper-service

but my settings have not been loaded

**Comment by sezanzeb** [comment]
after a reboot?

If XAUTHORITY has any influence on systemd services then there is something seriously going wrong with your system, because
1. XAUTHORITY is X, which only starts after the system has booted completely afaik
2. ~/.Xauthority is in your home directory, so it can only be relevant after you logged in

**Comment by chorriwuarri** [comment]
si, esto después de un reinicio, como le digo esto solo me ocurre en sway, funciona bien en gnome

**Comment by sezanzeb** [comment]
wow

**Comment by chorriwuarri** [comment]
the rest of the systemd services work fine, I don't have any errors and I have several as tlp

**Comment by sezanzeb** [comment]
key-mapper-service only needs evdev and dbus. It will start even without X/Wayland/Sway installed at all. I don't know what kind of weird stuff sway does, but I'll make sure to never use it on my installations.

If sway affects services that are set up to start before you even logged in there is something incredibly broken in my opinion, not with key-mapper, but with sway. sorry

**Comment by sezanzeb** [comment]
anyway, I hope you'll still enjoy key mapper and if you have feature requests or observe bugs during operation feel free to open more issues.

**Comment by chorriwuarri** [comment]
thank you very much for your help

I have to continue investigating because now I don't get systemd error with key-mapper but it doesn't load my configuration, I have to load it manually at each reboot.

I am with sway for fun, in fact my gpu is nvidia and the sway dev hates me for it.

**Comment by sezanzeb** [comment]
autoloading at login happens via this file: https://github.com/sezanzeb/key-mapper/blob/main/data/key-mapper-autoload.desktop

All you need to do is figure out where to save the command from the .desktop file so that it happens after your login.

**Comment by chorriwuarri** [comment]
oh thank you very much this did the job
