### ISSUE TITLE
loading configuration failed

### ISSUE THREAD

**Issue by pablokal** [sezanzeb/key-mapper#216]
keymapper
Loading configuration failed
[paul@paulsam ~]$ sudo pkill -f key-mapper-service && key-mapper-gtk -d
bash: key-mapper-gtk: command not found

keymapper
Loading configuration failed
[paul@paulsam ~]$ sudo pkill -f key-mapper-service && key-mapper-gtk -d
bash: key-mapper-gtk: command not found

archbang openbox

echo $XDG_SESSION_TYPE
tty
sudo ls -l /proc/1/exe
lrwxrwxrwx 1 root root 0 Nov 27 10:15 /proc/1/exe -> /usr/lib/systemd/systemd

cat ~/.config/key-mapper/config.json
cat: /home/paul/.config/key-mapper/config.json: No such file or directory
So doesn't seem installed but no  error messages upon installation  via yaayAnd keymapper and keymapperd are  in usr/bin

Please install the newest version from source to see if the problem has already been solved.

Share some logs please:

1. `key-mapper-control --version`
2. which linux distro (ubuntu 20.04, manjaro, etc.)
3. `echo $XDG_SESSION_TYPE`
4. which desktop environment (gnome, plasma, xfce4, etc.)
5. `sudo ls -l /proc/1/exe`

6. `cat ~/.config/key-mapper/config.json`
7. `key-mapper-control --command hello`
8. `systemctl status key-mapper -n 50`
9. `sudo pkill -f key-mapper-service && sudo key-mapper-service -d & sleep 2 && key-mapper-control --command autoload`, are your keys mapped now?
10. (while the previous command is still running) `sudo evtest` and search for a device suffixed by "mapped". Select it, does it report any events? Share the output.

**Comment by pablokal** [comment]
I nstalled with pacuar keymapper-git latest-2; same error

**Comment by sezanzeb** [comment]
Please take some time to format the issue correctly.

> yaayAnd keymapper and keymapperd are in usr/bin

1. Put newlines where appropriate
2. both "keymapper" "keymapperd" are not names that can be found in /usr/bin. Are you talking about key-mapper-service?

> keymapper
> Loading configuration failed
> [paul@paulsam ~]$ sudo pkill -f key-mapper-service && key-mapper-gtk -d
> bash: key-mapper-gtk: command not found

Where does "Loading configuration failed" come from? Where does "keymapper" come from? ´

You said some files can be found in /usr/bin, yet here it says "command not found"

**Comment by pablokal** [comment]
Where does "Loading configuration failed" come from? 
Yes, console output.
 Sorry for the clumsy input; I was in a hurry.
In ~/paul/.config there is no keymapper folder.
Yet when exploring with spacefm in root /usr/bin but keymapper and keymapperd are present. So it must be an incomplete installation.

**Comment by sezanzeb** [comment]
`keymapperd` is not a word that exists

**Comment by sezanzeb** [comment]
Furthermore, `Loading configuration failed` is not a string that can be found in the code.

Whatever you are doing and whatever you are looking at, you did not install key-mapper

**Comment by sezanzeb** [comment]
You installed this: https://github.com/houmain/keymapper

**Comment by pablokal** [comment]
Hi Tobi,
My sincere apologies for wasting your time.
Feel very embarassed. To my defence  I can put that I'm suffering form
macula degeneration, which means that I miss some field of vision. The
problem is that you don´t know when you miss something, because it's never
the same. Anyway... What I learn from this that I shouldn´t try to do some
things anymore as I did formerly. Accept my limitations. Thank you for your
work and kindness.
Greets Paul

Op zo 28 nov. 2021 om 11:07 schreef Tobi ***@***.***>:

**Comment by sezanzeb** [comment]
I'm sorry to hear that and I wish you all the best for the future.

No harm done

**Comment by sezanzeb** [comment]
Also, the name of the two projects is different by only a single letter and therefore easy to mistake.
