### ISSUE TITLE
Can't open the GUI if user is not part of the "input" group

### ISSUE THREAD

**Issue by lululock71** [sezanzeb/key-mapper#217]
Hi,
The title is self explanatory but I'll give more details here :
**System :** ArchLinux 5.15.2-arch1-1
**DE :** KDE Plasma 5.23.3
**Issue :** Can't open the GUI, asks for authentication but neither the _wheel_ user password or the _root_ password work (always says access denied).
**Solution :** Add the _wheel_ user to the _input_ group
`gpasswd -a user input`

It would be nice to precise in the installation process to add the user to the _input_ group if the GUI can't be opened.

**Comment by sezanzeb** [comment]
what is a "wheel" user? Is that your personal user?

Being in the input group hasn't been a requirement anymore for at least 6 months now, which version are you on?

**Comment by sezanzeb** [comment]
Other than that, having to add yourself to the input group in order to pass the pkexec test seems incredibly unlikely.

You are talking about this window, right?

![image](https://user-images.githubusercontent.com/28510156/143738344-66253d85-c1dc-4848-a0e6-0e3ceaf76480.png)

This is controlled by this .policy file: https://github.com/sezanzeb/key-mapper/blob/main/data/key-mapper.policy just like any other application that uses pkexec, there is no mention of "input" anywhere

**Comment by lululock71** [comment]
When I say the _wheel_ user, I mean the user for which its main group is _wheel_. I have multiple users on my machine. Mine has the rights to run _sudo_, others don't for security reasons.

I'm running the latest version available in the AUR :
`key-mapper 1.2.1 6a68b894dc44c20ad20fe2b3600adab21410b8a3 https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0
`
Freshly downloaded from the AUR (the PKGBUILD may be out of date ?)

I got a similar authentication window but if my user is not part of the _input_ group, neither my password or the _root_ password grant me access to the app :
![Screenshot_20211128_100456](https://user-images.githubusercontent.com/58026350/143742970-77687f9c-a1c6-4bd9-92fd-2d2e84a5018f.png)

Translation : "_Authentication failed. Please try again._"

I can't get the window open, and I'm absolutely sure my passwords are correct.

After adding my user to the _input_ group, entering my password grant me access and opens the GUI.

May be a policy issue from my side, but it is worth noting that I've done absolutely nothing to manage policies on that Arch install. I've simply followed the wiki and went lazy about setting up access to all the users.

**Comment by sezanzeb** [comment]
Does pkexec work for other applications? I.e. `pkexec gedit`?

**Comment by lululock71** [comment]
After removing my user from the _input_ group and rebooting, running `pkexec nano` gives me a authentication prompt and putting my user password work and _nano_ opens in my terminal.

What's weird is that now, _key-mapper_ does launch when entering my user password while I'm not part of the _input_ group anymore...
`~/ groups`
`power users storage wheel
`

Maybe a _polkit_ bug ?

**Comment by sezanzeb** [comment]
maybe. I don't think key-mapper is doing anything out of the ordinary there. Here is their repo: https://gitlab.freedesktop.org/polkit/polkit/

**Comment by lululock71** [comment]
I'm not familiar with the _key-mapper_ code, so I thought it might be a related issue.
Anyway, thanks for helping me out.

The issue is closed, as it is not a _key-mapper_ related issue.
