### ISSUE TITLE
When to update the software release

### ISSUE THREAD

**Issue by jim8989** [sezanzeb/key-mapper#22]
I'm running v 0.5.0 and it's doing a fine job of inputting the keystrokes for mouse button 2, 6 and 7.  Thanks again for you help in getting button 6 & 7 working. Now I see your up to v 0.6.0
 
I don't see me adding additional key and mapping statements to add functionality to the installed software at least at this time. Do you feel that it's necessary that I keep up with new releases as you publish them if the three buttons are working correctly?

Jim

**Comment by sezanzeb** [comment]
no, not necessary.

since your wheel buttons 6 and 7 are working you already have quite a lot of 0.6.0 locally already.
