### ISSUE TITLE
Detected name showing up as "unknown" in GUI

### ISSUE THREAD

**Issue by jose1711** [sezanzeb/key-mapper#222]
It's only an aesthetic issue (mapped key works) but still.. one of the buttons on my Logitech G300s gaming mouse show up as "unknown" in the GUI.

![obrázok](https://user-images.githubusercontent.com/1406222/144497868-3706cf78-cade-4b80-88c9-e855d0c243aa.png)

The button corresponds to G9:
![obrázok](https://user-images.githubusercontent.com/1406222/144498097-7c79b0eb-63a4-40d0-b576-48e22cf83eb0.png)

This is what shows up on the console:
```
ERROR: Unknown key code for (1, 280, 1)
```
Output from `xev`:
```
ButtonPress event, serial 36, synthetic NO, window 0x6200001,
    root 0x1dd, subw 0x0, time 11673191, (115,113), root:(3353,188),
    state 0x10, button 13, same_screen YES

ButtonRelease event, serial 36, synthetic NO, window 0x6200001,
    root 0x1dd, subw 0x0, time 11673329, (115,113), root:(3353,188),
    state 0x10, button 13, same_screen YES
```

**Comment by sezanzeb** [comment]
how does `sudo evtest` show it?

**Comment by jose1711** [comment]
```
/dev/input/event256:	Logitech G300s Optical Gaming Mouse
/dev/input/event257:	Logitech G300s Optical Gaming Mouse Keyboard
/dev/input/event258:	Logitech G300s Optical Gaming Mouse
```
from `event256`:
```
Event: time 1638478849.688524, -------------- SYN_REPORT ------------
Event: time 1638478850.080565, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90009
Event: time 1638478850.080565, type 1 (EV_KEY), code 280 (?), value 1
Event: time 1638478850.080565, -------------- SYN_REPORT ------------
Event: time 1638478850.482526, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90009
Event: time 1638478850.482526, type 1 (EV_KEY), code 280 (?), value 0
Event: time 1638478850.482526, -------------- SYN_REPORT ------------
```

**Comment by sezanzeb** [comment]
Would showing `280` be better than `unknown`?

**Comment by jose1711** [comment]
> Would showing 280 be better than unknown?

Yeah, that does sound better. Anyway, I remapped the button using `ratslap` (can't remember the previous setting) and `unknown` is now gone. It's still possible to run into this situation if a user does something stupid though.

**Comment by sezanzeb** [comment]
Pushed a change for this to main. thanks
