### ISSUE TITLE
key-mapper does not work in all software, but why?

### ISSUE THREAD

**Issue by daniel88kary** [sezanzeb/key-mapper#238]
Before moving from Windows to Linux, I used AutoHotkey in Windows with the same mapped keys. It worked in every software. My goal is to be able to use the "AltGr"-key (german-layout) with the "w", "a", "s", "d" keys to move the cursor in every application.

I use Manjaro (KDE) and Linux Mint (Cinnamon), with both systems i have the same problem.
I use a german-layout-keyboard and use these mapped keys:
![mapped keys](https://user-images.githubusercontent.com/96523324/147075641-fca71622-ceca-4f12-8919-0eef26f773a2.png)
Here is the corresponding json-file:
[Meine Hotkeys.json.txt](https://github.com/sezanzeb/key-mapper/files/7761971/Meine.Hotkeys.json.txt)

The mapped keys are working in Visual Studio Code, Texmaker, Firefox, etc.
The mapped keys are **not** working in Matlab, TeXstudio, etc.

Why does it depend on the application?

**Comment by sezanzeb** [comment]
It could be because matlab sees `Shift + ctrl + x` instead of `ctrl + x`. Have you seen https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md#combinations?

**Comment by daniel88kary** [comment]
It works now 😁 great tool, great job👍👍thx for your help
I didn't realize that key-mapper could do so much

Here is my solution:
![mapped keys_v2](https://user-images.githubusercontent.com/96523324/147115370-2525c9af-526a-411c-8e70-8176e94bd655.png)
 Here is the corresponding json-file:
[Meine Hotkeys_v2.json.txt](https://github.com/sezanzeb/key-mapper/files/7763525/Meine.Hotkeys_v2.json.txt)
