### ISSUE TITLE
F11 + shift_L or F11 + shift_R

### ISSUE THREAD

**Issue by sonwh98** [sezanzeb/key-mapper#242]
my laptop keyboard got water damage and now left shift key maps to F11+shiftL and right shift key maps to F11+shiftR

in the GUI, i map those key combination to SHIFT_L and SHIFT_R respectively however its not working at the terminal.
It maps to repeated ~;2 instead

when I map it to "a", I get "~a". when I keep the shift key pressed I get "~aaaaaaaaaaa" 

However, the mapping f11+ShiftL to Shift_L works  in emacs as well as a shell within emacs

**Comment by sezanzeb** [comment]
if you map `F11 + shift L` to `Shift L` it won't actually do anything.

Like this, right?

![image](https://user-images.githubusercontent.com/28510156/147610752-a2ac6b3d-571b-4ad0-b47f-365a91f7b049.png)

1. F11 key event arrives
2. F11 is forwarded to the desktop environment by key-mapper
3. Shift_L key event arrives
4. key-mapper maps `F11 + Shift_L` to `Shift_L` and injects that

so the result is that `F11` and `Shift_L` are injected.

**Comment by sezanzeb** [comment]
You can disable the `F11` key by mapping it to `disable`:

![image](https://user-images.githubusercontent.com/28510156/147611054-150aafcf-3cdc-427c-a7f2-f208d4e7fed6.png)

Which is what I think you are trying to do

**Comment by sonwh98** [comment]
I am unable to use the GUI to find the key code for F11 but then i started the GUI with `key-mapper-gtk -d` and saw the keycode for the F11 key was `1,87,1` which I mapped to `Shift_L`

here's my `~/.config/key-mapper/presets/AT Translated Set 2 keyboard/shift.json` preset
```json
{
    "mapping": {
        "1,87,1": "Shift_L"
    }
}
```json

thanks a lot! you've saved me from spending $3k on another laptop

**Comment by sezanzeb** [comment]
> I am unable to use the GUI to find the key code for F11

ah right, I forgot.

Good job correctly figuring it out! Thanks!
