### ISSUE TITLE
Renaming the preset in the gui does not update the preset in the autoload section in config.json

### ISSUE THREAD

**Issue by michael-oti** [sezanzeb/key-mapper#247]
OS: Arch (wayland)

`key-mapper-control --version`
key-mapper 1.2.2 3892789b73313086c57bec600f0acb68022acb1c https://github.com/sezanzeb/key-mapper
python-evdev 1.4.0

Renaming the preset in the gui does not update the preset in the autoload section in config.json. The preset in the presets folder gets renamed. One has to toggle the autoload button off and one again for it to update.

**Comment by sezanzeb** [comment]
Wow, I can't believe it took so long for anyone to notice

I'll fix it soon. thanks for reporting

**Comment by sezanzeb** [comment]
fix pushed to main
