### ISSUE TITLE
Key Mapper can't map brightness keys

### ISSUE THREAD

**Issue by FireballFoxtrot** [sezanzeb/key-mapper#27]
My keyboard has a very strange layout, which replaces the F keys with media controls despite Fn + F keys already being media controls. For certain keys, this program seems to work very well, but it doesn't appear to be able to pick up everything. F1 and F2 are monitor brightness up and down respectively, and key mapper can't read either one as inputs. Is there any workaround for this?

**Comment by sezanzeb** [comment]
I can confirm that brightness keys don't work. While there is a device with `KEY_BRIGHTNESSDOWN` and `KEY_BRIGHTNESSUP` capabilities on my laptop, those keys don't seem to report events via evdev. So it won't be possible to map them via key-mapper.

You might have luck finding a way to configure your F and Fn key behaviour in the bios.

**Comment by FireballFoxtrot** [comment]
I've already looked, and my bios doesn't have any settings for Fn key behavior; besides, that might not even fix my issue. I've booted into windows and the keyboard works as intended. The strangest part here is that despite linux changing the F key inputs to media controls, the Fn + F keys still do media controls anyway. So I just have two rows of media controls, some of which are just redundant.

**Comment by sezanzeb** [comment]
This is the first time I heard of that issue unfortunately

**Comment by FireballFoxtrot** [comment]
I'm currently on an MX linux system using xfce4

**Comment by sezanzeb** [comment]
Let me know if you tried gnome on wayland on the laptop. Maybe I can also just do it over the weekend on mine if you don't have time. I'm also running xfce4

**Comment by sezanzeb** [comment]
I just tried it on my laptop with gnome on wayland and evtest still doesn't report brightness key events (which is expected tbh, evdev doesn't talk to the window manager). It also won't work in my tty. And upgrading the kernel just broke my brightness keys for good. I don't think there is a workaround for it.
