### ISSUE TITLE
Windows release?

### ISSUE THREAD

**Issue by rayman3003** [sezanzeb/key-mapper#3]
Could we see a Windows release for key-mapper?

**Comment by sezanzeb** [comment]
I don't use Windows, so I personally won't develop Windows support, sorry.

If anyone wants to make this happen, you can try to make something for windows that works like a drop in replacement for python-evdev (https://github.com/gvalkov/python-evdev/pull/145). But I won't be able to maintain it as part of this repo.

**Comment by rayman3003** [comment]
Two years passed & the name of the app also changed!

Maybe now u have a possibility for working on Windows version?

I would volunteer to test the windows version for u too.

**Comment by sezanzeb** [comment]
nope, sorry

**Comment by rayman3003** [comment]
OK, thank u.
