### ISSUE TITLE
Caps Lock as Escape and Control

### ISSUE THREAD

**Issue by likern** [sezanzeb/key-mapper#30]
Hello 👋. I have read description and couldn't find whether that's possible to map Caps Lock to act as Escape, and as Ctrl if pressed chorded with another key.

Also I've seen there is problems with Ctrl and Shift.
Have you looked at https://gitlab.com/interception/linux/tools, https://gitlab.com/interception/linux/plugins/caps2esc.

As I understand they fully intercept key presses, so noone, including window manager knows about original event. And they substitute them with their own.

This way any exotic combinations should work as it's done at earliest level.

At least this is the only solution that allowed we to reliably map Escape and Ctrl to Caps Lock simultaneously. Would be nice to have that ability in your GUI.

**Comment by sezanzeb** [comment]
> map Caps Lock to act as Escape, and as Ctrl if pressed chorded with another key.

just tried it and it works

![image](https://user-images.githubusercontent.com/28510156/106595830-6f116000-6554-11eb-8030-8256a3bf1629.png)

> As I understand they fully intercept key presses, so noone, including window manager knows about original event. And they substitute them with their own.

sounds like what key-mapper is doing

**Comment by likern** [comment]
@sezanzeb Hello. I tried and it does't work.

Approaches:
1. Generates `escape` if I press CapsLock + Key. So that `escape` breaks how application behaving. For example for vim editor: If I try to press combination CapsLock + Key it gets `escape` also and changes it's editor mode.
2. Disables some key

What I'm talking about:
1. All usual keys are behaving as usual
2. If I press **only CapsLock button** it will behave as Escape.
3. If I press CapsLock simulteniously with other usual key (CapsLock + Key) it will behave as Ctrl + Key.
4. That works for **any key**, but for some exact one. And without disabling usual key behaviour.

In https://gitlab.com/interception/linux/tools approach **CapsLock behaves as two separate buttons** - Escape (which is never pressed in combination with other key) and Ctrl + Key (because Ctrl is never pressed on it's own, only in combination).

**Comment by likern** [comment]
Main logic is here: https://gitlab.com/interception/linux/plugins/caps2esc/-/blob/master/caps2esc.c#L92.

**Comment by sezanzeb** [comment]
ah, so you mean "and as Ctrl if pressed chorded with another **arbitrary** key."

is escape injected when you release CapsLock on that other solution?

**Comment by likern** [comment]
> ah, so you mean capslock + any other arbitrary key of the whole keyboard = ctrl + that key

Yes

> is escape injected when you release or press CapsLock on that other solution? It probably waits for the release event of caps or for the down-event of any other key.

Yes, I've grabbed keys using `xev`.
If I press **only** `CapsLock` nothing happens while it has been pressing. I soon as I release it I see these events
```bash
KeyPress event, serial 37, synthetic NO, window 0x3600001,
    root 0x6c8, subw 0x0, time 25972252, (1432,590), root:(1482,704),
    state 0x10, keycode 9 (keysym 0xff1b, Escape), same_screen YES,
    XLookupString gives 1 bytes: (1b) "
mbLookupString gives 1 bytes: (1b) "
FilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3600001,
    root 0x6c8, subw 0x0, time 25972271, (1432,590), root:(1482,704),
    state 0x10, keycode 9 (keysym 0xff1b, Escape), same_screen YES,
    XLookupString gives 1 bytes: (1b) "
FilterEvent returns: False
```

If I press `CapsLock + j` key, for example, I see these events
```bash
KeyPress event, serial 37, synthetic NO, window 0x3600001,
    root 0x6c8, subw 0x0, time 26258006, (1244,622), root:(1294,736),
    state 0x10, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x3600001,
    root 0x6c8, subw 0x0, time 26258026, (1244,622), root:(1294,736),
    state 0x14, keycode 46 (keysym 0x6c, l), same_screen YES,
    XLookupString gives 1 bytes: (0c) "
                                       "
    XmbLookupString gives 1 bytes: (0c) "
                                         "
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3600001,
    root 0x6c8, subw 0x0, time 26258102, (1244,622), root:(1294,736),
    state 0x14, keycode 46 (keysym 0x6c, l), same_screen YES,
    XLookupString gives 1 bytes: (0c) "
                                       "
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3600001,
    root 0x6c8, subw 0x0, time 26263310, (1244,622), root:(1294,736),
    state 0x14, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Yes, it waits until release event (if no other key was pressed) and when I release `CapsLock` it emits two events (for pressing and releasing key, emulating full normal press).

I understand that it might be a little bit hacky, but in practice, in real life usage that solution works really well.

**Comment by sezanzeb** [comment]
The macro system is able to wait until the key is released. For example `h().k(a)` will write a-down and a-up when the key is released.

But there is currently no way to
- tell the macro to stop when another macro (the combination caps + any) is triggered
- map "any" key. It would have to be a macro that waits until another key is pressed, remember it and write it later

Sounds complicated. I think the architecture is already quite complex in order to support combinations and gamepad events.

---

The second option would be to map caps-release to a macro. If that would work (and it most likely doesn't at the moment since only key-down events trigger stuff) it would not start the macro if combined, because key combinations take priority. But then again, there is no way to map combinations with "any" key currently.

It might work by supporting wildcards in the .json config files, which could be recognized in `_map_keys_to_codes`

**Comment by sezanzeb** [comment]
What is wrong with caps2esc that make you look for alternatives?

**Comment by likern** [comment]
> What is wrong with caps2esc that makes you look for alternatives?

If you want to extend this thing, you have have to dig into and write own C code with low-level understanding of Linux Input Subsystem. Let's say own program for caps2meta, etc. 

I don't think I have to write and compile code for any remapping. I want something easy to use.

For example I'm thinking about remaining numbers to cluster in uio,jkl,nm, position so do not need to stretch to numbers keys. They are heavily used in programming and vim editor combination. 

There is also a lot of interesting things can be done to improve day-to-day experience and productivity. Which makes huge difference in comparison.

**Comment by sezanzeb** [comment]
I'm not yet sure if this will be possible, I'll keep this ticket closed until then.

**Comment by sezanzeb** [comment]
see https://github.com/sezanzeb/key-mapper/issues/183

**Comment by im-AMS** [comment]
@sezanzeb can you help me figure this out?
- JUST Caps - Esc
- Shift+Caps - Caps
- Caps key+Backspace - Ctrl+Backspace
- Caps Key+j - Arrow Down
- Caps Key+k - Arrow Up
- Caps Key+l - Arrow Right
- Caps Key+h - Arrow left

**Comment by sezanzeb** [comment]
try mapping caps to `if_single(key(KEY_ESC))`, and add the other mappings as you described

**Comment by Bad3r** [comment]
is `if_single` supported on v2? I can't find it in the documentation, and the syntax for mapping changed.
