### ISSUE TITLE
[Feature Request]: presets assigned to programs

### ISSUE THREAD

**Issue by mauritzn** [sezanzeb/key-mapper#32]
Would be lovely if you could mark a preset as default and then have others that would activate when you focus a specific program/game.

Not sure if this is already planned or if this would just be a giant pain to add... But thought I should at least put it out there

**Best regards,**
Mauritz

**Comment by sezanzeb** [comment]
It would be really nice if that could work, but unfortunatelly wayland hides those things https://github.com/sezanzeb/key-mapper/discussions/20

**Comment by mauritzn** [comment]
> It would be really nice if that could work, but unfortunately wayland hides those things. See #20

ahh okay, thanks for the quick reply

**Comment by jose1711** [comment]
I think this would still be useful even without knowing which windows is in focus. Imagine a single controller with a 3 independent mapping (similar to how Steam controller works in Steam client). The only thing you'd need to know is a process name as you're not really expected to play the games simultaneously.

**Comment by mauritzn** [comment]
> I think this would still be useful even without knowing which windows is in focus. Imagine a single controller with a 3 independent mapping (similar to how Steam controller works in Steam client). The only thing you'd need to know is a process name as you're not really expected to play the games simultaneously.

Mmh, could actually be quite useful to map presets to running processes, have a few scenarios myself where that would be quite handy, not sure how easy it would be to implement, but would love to know how feasible it would be to implement 👍

Of course could be a bit interesting how it would handle a scenario where multiple presets have running processes that match... A priority setting added to each could probably solve that, but could get messy...

**Comment by sezanzeb** [comment]
> The only thing you'd need to know is a process name as you're not really expected to play the games simultaneously.

good point. Lets make this another issue and label it as feature request

**Comment by jose1711** [comment]
> > The only thing you'd need to know is a process name as you're not really expected to play the games simultaneously.
> 
> good point. But would I have to check periodically for the presence of the game process? How fast is fast enough, is it easy on system resources to get a list of running processes?

Based on my observations lightweight passive monitoring tools tend to do such checks every minute at most. I think 60 seconds between process checks would be acceptable (unless a player switches between games several times in a minute - in that case the process matching should simply be disabled). But best would be to get data from tests in a real-life situations.
