### ISSUE TITLE
0.6.1 freezes the pointer when applying a profile

### ISSUE THREAD

**Issue by CarlosEkisde** [sezanzeb/key-mapper#35]
0.6.1 freezes the pointer when applying a profile, only way to restore the normal behaviour is unplugging and plugging it again. The profile doesn't work anyway. Console shows no error messages. 0.6.0 seems to be fine.

This is an excellent piece of software by the way. I hope it will arrive soon to every distro repo. Congratulations to the author.

Edit: I forgot to add the specs of my machine: Fedora 33 KDE on X11 with nvidia proprietary driver.

**Comment by sezanzeb** [comment]
pressing `shift` + `del` on your keyboard should also work to recover your mouse

I'd like to see the debug output of the service. For that, please do:

```
sudo systemctl stop key-mapper
sudo key-mapper-service -d
```

now open the user interface and apply the preset, such that the mouse won't move anymore.

Please post the output here. Thanks!

**Comment by CarlosEkisde** [comment]
`0.03942 INFO: logger.py, line 194, This output is also stored in "/root/.log/key-mapper"
0.03998 INFO: logger.py, line 208, Logging to "/root/.log/key-mapper/log"
0.06156 INFO: logger.py, line 154, key-mapper 0.6.1 
0.06207 INFO: logger.py, line 157, python-evdev 1.1.2
0.06223 WARNING: logger.py, line 163, Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
0.06234 DEBUG: logger.py, line 169, pid 10263
0.06409 DEBUG: daemon.py, line 133, Creating daemon
15.4938 INFO: config.py, line 246, Loaded config from "/home/xxxxx/.config/key-mapper/config.json"
15.5007 DEBUG: getdevices.py, line 104, Discovering device paths
15.5034 SPAM: getdevices.py, line 142, Found "3,1390,254", "/dev/input/event6", "ELECOM ELECOM TrackBall Mouse" 
15.5038 SPAM: getdevices.py, line 142, Found "3,1266,1026", "/dev/input/event5", "Chicony USB Keyboard Consumer Control" 
15.5040 SPAM: getdevices.py, line 142, Found "3,1266,1026", "/dev/input/event4", "Chicony USB Keyboard System Control" 
15.5044 SPAM: getdevices.py, line 142, Found "3,1266,1026", "/dev/input/event3", "Chicony USB Keyboard" 
15.5046 SPAM: getdevices.py, line 142, Found "25,0,3", "/dev/input/event0", "Sleep Button" 
15.5052 INFO: getdevices.py, line 201, Found "ELECOM ELECOM TrackBall Mouse", "Chicony USB Keyboard", "Sleep Button"
15.5055 INFO: mapping.py, line 164, Loading preset from "/home/xxxxx/.config/key-mapper/presets/ELECOM ELECOM TrackBall Mouse/gaming.json"
15.5059 SPAM: mapping.py, line 197, Key((1, 277, 1),) maps to 2
15.5062 SPAM: mapping.py, line 197, Key((1, 275, 1),) maps to 1
15.5064 SPAM: mapping.py, line 197, Key((1, 278, 1),) maps to 3
15.5066 SPAM: mapping.py, line 197, Key((1, 279, 1),) maps to 4
15.5068 SPAM: mapping.py, line 197, Key((2, 6, -1),) maps to 0
15.5071 SPAM: mapping.py, line 197, Key((2, 6, 1),) maps to 9
15.5073 SPAM: mapping.py, line 197, Key((1, 276, 1),) maps to 8
15.5081 DEBUG: daemon.py, line 198, Using keycodes from "/home/xxxxx/.config/key-mapper/xmodmap.json"
15.5359 INFO: pid 10291, injector.py, line 398, Starting injecting the mapping for "ELECOM ELECOM TrackBall Mouse"
15.5375 DEBUG: pid 10291, injector.py, line 277, Grab /dev/input/event6
15.5378 DEBUG: pid 10291, injector.py, line 413, Parsing macros for /dev/input/event6
15.5380 DEBUG: pid 10291, injector.py, line 425, No macros configured
15.6485 SPAM: pid 10291, injector.py, line 437, Injected capabilities for "/dev/input/event6": {('EV_SYN', 0): [('SYN_REPORT', 0), ('SYN_CONFIG', 1), ('SYN_MT_REPORT', 2), ('SYN_DROPPED', 3), ('?', 4), ('?', 21)], ('EV_KEY', 1): [('KEY_ESC', 1), ('KEY_1', 2), ('KEY_2', 3), ('KEY_3', 4), ('KEY_4', 5), ('KEY_8', 9), ('KEY_9', 10), ('KEY_0', 11), ('KEY_ENTER', 28), ('KEY_KPMINUS', 74), ('KEY_KPPLUS', 78), ('KEY_UP', 103), ('KEY_LEFT', 105), ('KEY_RIGHT', 106), ('KEY_DOWN', 108), (['KEY_MIN_INTERESTING', 'KEY_MUTE'], 113), ('KEY_VOLUMEDOWN', 114), ('KEY_VOLUMEUP', 115), ('KEY_POWER', 116), ('KEY_PAUSE', 119), ('KEY_STOP', 128), ('KEY_PROPS', 130), ('KEY_UNDO', 131), ('KEY_COPY', 133), ('KEY_OPEN', 134), ('KEY_PASTE', 135), ('KEY_FIND', 136), ('KEY_CUT', 137), ('KEY_HELP', 138), ('KEY_MENU', 139), ('KEY_CALC', 140), ('KEY_SLEEP', 142), ('KEY_WAKEUP', 143), ('KEY_FILE', 144), ('KEY_WWW', 150), (['KEY_COFFEE', 'KEY_SCREENLOCK'], 152), ('KEY_MAIL', 155), ('KEY_BOOKMARKS', 156), ('KEY_BACK', 158), ('KEY_FORWARD', 159), ('KEY_EJECTCD', 161), ('KEY_NEXTSONG', 163), ('KEY_PLAYPAUSE', 164), ('KEY_PREVIOUSSONG', 165), ('KEY_STOPCD', 166), ('KEY_RECORD', 167), ('KEY_REWIND', 168), ('KEY_PHONE', 169), ('KEY_CONFIG', 171), ('KEY_HOMEPAGE', 172), ('KEY_REFRESH', 173), ('KEY_EXIT', 174), ('KEY_SCROLLUP', 177), ('KEY_SCROLLDOWN', 178), ('KEY_NEW', 181), ('KEY_CLOSE', 206), ('KEY_PLAY', 207), ('KEY_FASTFORWARD', 208), ('KEY_BASSBOOST', 209), ('KEY_PRINT', 210), ('KEY_CAMERA', 212), ('KEY_CHAT', 216), ('KEY_SEARCH', 217), ('KEY_FINANCE', 219), ('KEY_BRIGHTNESSDOWN', 224), ('KEY_BRIGHTNESSUP', 225), ('KEY_KBDILLUMTOGGLE', 228), ('KEY_KBDILLUMDOWN', 229), ('KEY_KBDILLUMUP', 230), ('KEY_SAVE', 234), ('KEY_DOCUMENTS', 235), ('KEY_UNKNOWN', 240), ('KEY_VIDEO_NEXT', 241), (['KEY_BRIGHTNESS_AUTO', 'KEY_BRIGHTNESS_ZERO'], 244), (['BTN_0', 'BTN_MISC'], 256), (['BTN_LEFT', 'BTN_MOUSE'], 272), ('BTN_RIGHT', 273), ('BTN_MIDDLE', 274), ('BTN_SIDE', 275), ('BTN_EXTRA', 276), ('BTN_FORWARD', 277), ('BTN_BACK', 278), ('BTN_TASK', 279), ('KEY_SELECT', 353), ('KEY_GOTO', 354), ('KEY_INFO', 358), ('KEY_PROGRAM', 362), ('KEY_PVR', 366), ('KEY_SUBTITLE', 370), (['KEY_FULL_SCREEN', 'KEY_ZOOM'], 372), ('KEY_KEYBOARD', 374), (['KEY_ASPECT_RATIO', 'KEY_SCREEN'], 375), ('KEY_PC', 376), ('KEY_TV', 377), ('KEY_TV2', 378), ('KEY_VCR', 379), ('KEY_VCR2', 380), ('KEY_SAT', 381), ('KEY_CD', 383), ('KEY_TAPE', 384), ('KEY_TUNER', 386), ('KEY_PLAYER', 387), ('KEY_DVD', 389), ('KEY_AUDIO', 392), ('KEY_VIDEO', 393), ('KEY_MEMO', 396), ('KEY_CALENDAR', 397), ('KEY_RED', 398), ('KEY_GREEN', 399), ('KEY_YELLOW', 400), ('KEY_BLUE', 401), ('KEY_CHANNELUP', 402), ('KEY_CHANNELDOWN', 403), ('KEY_LAST', 405), ('KEY_NEXT', 407), ('KEY_RESTART', 408), ('KEY_SLOW', 409), ('KEY_SHUFFLE', 410), ('KEY_PREVIOUS', 412), ('KEY_VIDEOPHONE', 416), ('KEY_GAMES', 417), ('KEY_ZOOMIN', 418), ('KEY_ZOOMOUT', 419), ('KEY_ZOOMRESET', 420), ('KEY_WORDPROCESSOR', 421), ('KEY_EDITOR', 422), ('KEY_SPREADSHEET', 423), ('KEY_GRAPHICSEDITOR', 424), ('KEY_PRESENTATION', 425), ('KEY_DATABASE', 426), ('KEY_NEWS', 427), ('KEY_VOICEMAIL', 428), ('KEY_ADDRESSBOOK', 429), ('KEY_MESSENGER', 430), (['KEY_BRIGHTNESS_TOGGLE', 'KEY_DISPLAYTOGGLE'], 431), ('KEY_SPELLCHECK', 432), ('KEY_LOGOFF', 433), ('KEY_MEDIA_REPEAT', 439), ('KEY_IMAGES', 442), ('KEY_BUTTONCONFIG', 576), ('KEY_TASKMANAGER', 577), ('KEY_JOURNAL', 578), ('KEY_CONTROLPANEL', 579), ('KEY_APPSELECT', 580), ('KEY_SCREENSAVER', 581), ('KEY_VOICECOMMAND', 582), ('KEY_ASSISTANT', 583), ('KEY_BRIGHTNESS_MIN', 592), ('KEY_BRIGHTNESS_MAX', 593)], ('EV_REL', 2): [('REL_X', 0), ('REL_Y', 1), ('REL_HWHEEL', 6), ('REL_WHEEL', 8), ('REL_WHEEL_HI_RES', 11), ('REL_HWHEEL_HI_RES', 12)], ('EV_ABS', 3): [(('ABS_VOLUME', 32), AbsInfo(value=0, min=0, max=0, fuzz=0, flat=0, resolution=0))], ('EV_MSC', 4): [('MSC_SCAN', 4)]}
15.6557 DEBUG: pid 10291, injector.py, line 100, numlockx not found
15.6577 DEBUG: pid 10291, injector.py, line 513, Started consumer to inject to /dev/input/event6, fd 38
25.8895 INFO: injector.py, line 565, Stopping injecting keycodes for device "ELECOM ELECOM TrackBall Mouse"
25.8911 DEBUG: pid 10291, injector.py, line 372, Received close signal
25.8915 DEBUG: pid 10291, injector.py, line 488, asyncio coroutines ended
25.8980 DEBUG: injector.py, line 100, numlockx not found
`

**Comment by sezanzeb** [comment]
Thanks. I'll check if the capabilities are allright later.

Between 15.6577 and 25.8895 nothing happened? If you click buttons on your mouse, does the service log anything?

Can you also do the same for version 0.6.0 please? That might also help a lot

**Comment by CarlosEkisde** [comment]
Between 15.6 and 25.8 is probably the time when the profile was running.

`0.06832 INFO: logger.py, line 180, This output is also stored in "~/.log/key-mapper"
0.06867 INFO: logger.py, line 194, Logging to "/root/.log/key-mapper/log"
0.09134 INFO: logger.py, line 140, key-mapper 0.6.0
0.09173 INFO: logger.py, line 143, python-evdev 1.1.2
0.09182 WARNING: logger.py, line 149, Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
0.09195 DEBUG: logger.py, line 155, pid 13179
0.09551 DEBUG: daemon.py, line 133, Creating daemon
19.4286 INFO: config.py, line 245, Loaded config from "/home/xxxxx/.config/key-mapper/config.json"
19.4324 DEBUG: getdevices.py, line 100, Discovering device paths
19.4342 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 056e, product 00fe, version 0111", "/dev/input/event6", "ELECOM ELECOM TrackBall Mouse"
19.4344 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 04f2, product 0402, version 0111", "/dev/input/event5", "Chicony USB Keyboard Consumer Control"
19.4345 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 04f2, product 0402, version 0111", "/dev/input/event4", "Chicony USB Keyboard System Control"
19.4347 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 04f2, product 0402, version 0111", "/dev/input/event3", "Chicony USB Keyboard"
19.4349 SPAM: getdevices.py, line 126, Found "bus: 0019, vendor 0000, product 0003, version 0000", "/dev/input/event0", "Sleep Button"
19.4352 INFO: getdevices.py, line 189, Found "ELECOM ELECOM TrackBall Mouse", "Chicony USB Keyboard", "Sleep Button"
19.4354 INFO: mapping.py, line 162, Loading preset from "/home/xxxxx/.config/key-mapper/presets/ELECOM ELECOM TrackBall Mouse/gaming.json"
19.4357 SPAM: mapping.py, line 195, Key((1, 277, 1),) maps to 2
19.4359 SPAM: mapping.py, line 195, Key((1, 275, 1),) maps to 1
19.4360 SPAM: mapping.py, line 195, Key((1, 278, 1),) maps to 3
19.4362 SPAM: mapping.py, line 195, Key((1, 279, 1),) maps to 4
19.4363 SPAM: mapping.py, line 195, Key((2, 6, -1),) maps to 0
19.4365 SPAM: mapping.py, line 195, Key((2, 6, 1),) maps to 9
19.4366 SPAM: mapping.py, line 195, Key((1, 276, 1),) maps to 8
19.4371 DEBUG: daemon.py, line 196, Using keycodes from "/home/xxxxx/.config/key-mapper/xmodmap.json"
19.4650 INFO: pid 13207, injector.py, line 377, Starting injecting the mapping for "ELECOM ELECOM TrackBall Mouse"
19.4660 DEBUG: pid 13207, injector.py, line 258, Grab /dev/input/event6
19.4661 DEBUG: pid 13207, injector.py, line 392, Parsing macros for /dev/input/event6
19.4663 DEBUG: pid 13207, injector.py, line 404, No macros configured
19.5700 SPAM: pid 13207, injector.py, line 415, Injected capabilities for "/dev/input/event6": {('EV_SYN', 0): [('SYN_REPORT', 0), ('SYN_CONFIG', 1), ('SYN_MT_REPORT', 2), ('?', 4), ('?', 21)], ('EV_KEY', 1): [('KEY_ESC', 1), ('KEY_1', 2), ('KEY_2', 3), ('KEY_3', 4), ('KEY_4', 5), ('KEY_8', 9), ('KEY_9', 10), ('KEY_0', 11), ('KEY_ENTER', 28), ('KEY_KPMINUS', 74), ('KEY_KPPLUS', 78), ('KEY_UP', 103), ('KEY_LEFT', 105), ('KEY_RIGHT', 106), ('KEY_DOWN', 108), (['KEY_MIN_INTERESTING', 'KEY_MUTE'], 113), ('KEY_VOLUMEDOWN', 114), ('KEY_VOLUMEUP', 115), ('KEY_POWER', 116), ('KEY_PAUSE', 119), ('KEY_STOP', 128), ('KEY_PROPS', 130), ('KEY_UNDO', 131), ('KEY_COPY', 133), ('KEY_OPEN', 134), ('KEY_PASTE', 135), ('KEY_FIND', 136), ('KEY_CUT', 137), ('KEY_HELP', 138), ('KEY_MENU', 139), ('KEY_CALC', 140), ('KEY_SLEEP', 142), ('KEY_WAKEUP', 143), ('KEY_FILE', 144), ('KEY_WWW', 150), (['KEY_COFFEE', 'KEY_SCREENLOCK'], 152), ('KEY_MAIL', 155), ('KEY_BOOKMARKS', 156), ('KEY_BACK', 158), ('KEY_FORWARD', 159), ('KEY_EJECTCD', 161), ('KEY_NEXTSONG', 163), ('KEY_PLAYPAUSE', 164), ('KEY_PREVIOUSSONG', 165), ('KEY_STOPCD', 166), ('KEY_RECORD', 167), ('KEY_REWIND', 168), ('KEY_PHONE', 169), ('KEY_CONFIG', 171), ('KEY_HOMEPAGE', 172), ('KEY_REFRESH', 173), ('KEY_EXIT', 174), ('KEY_SCROLLUP', 177), ('KEY_SCROLLDOWN', 178), ('KEY_NEW', 181), ('KEY_CLOSE', 206), ('KEY_PLAY', 207), ('KEY_FASTFORWARD', 208), ('KEY_BASSBOOST', 209), ('KEY_PRINT', 210), ('KEY_CAMERA', 212), ('KEY_CHAT', 216), ('KEY_SEARCH', 217), ('KEY_FINANCE', 219), ('KEY_BRIGHTNESSDOWN', 224), ('KEY_BRIGHTNESSUP', 225), ('KEY_KBDILLUMTOGGLE', 228), ('KEY_KBDILLUMDOWN', 229), ('KEY_KBDILLUMUP', 230), ('KEY_SAVE', 234), ('KEY_DOCUMENTS', 235), ('KEY_UNKNOWN', 240), ('KEY_VIDEO_NEXT', 241), (['KEY_BRIGHTNESS_AUTO', 'KEY_BRIGHTNESS_ZERO'], 244), (['BTN_0', 'BTN_MISC'], 256), (['BTN_LEFT', 'BTN_MOUSE'], 272), ('BTN_RIGHT', 273), ('BTN_MIDDLE', 274), ('BTN_SIDE', 275), ('BTN_EXTRA', 276), ('BTN_FORWARD', 277), ('BTN_BACK', 278), ('BTN_TASK', 279), ('KEY_SELECT', 353), ('KEY_GOTO', 354), ('KEY_INFO', 358), ('KEY_PROGRAM', 362), ('KEY_PVR', 366), ('KEY_SUBTITLE', 370), (['KEY_FULL_SCREEN', 'KEY_ZOOM'], 372), ('KEY_KEYBOARD', 374), (['KEY_ASPECT_RATIO', 'KEY_SCREEN'], 375), ('KEY_PC', 376), ('KEY_TV', 377), ('KEY_TV2', 378), ('KEY_VCR', 379), ('KEY_VCR2', 380), ('KEY_SAT', 381), ('KEY_CD', 383), ('KEY_TAPE', 384), ('KEY_TUNER', 386), ('KEY_PLAYER', 387), ('KEY_DVD', 389), ('KEY_AUDIO', 392), ('KEY_VIDEO', 393), ('KEY_MEMO', 396), ('KEY_CALENDAR', 397), ('KEY_RED', 398), ('KEY_GREEN', 399), ('KEY_YELLOW', 400), ('KEY_BLUE', 401), ('KEY_CHANNELUP', 402), ('KEY_CHANNELDOWN', 403), ('KEY_LAST', 405), ('KEY_NEXT', 407), ('KEY_RESTART', 408), ('KEY_SLOW', 409), ('KEY_SHUFFLE', 410), ('KEY_PREVIOUS', 412), ('KEY_VIDEOPHONE', 416), ('KEY_GAMES', 417), ('KEY_ZOOMIN', 418), ('KEY_ZOOMOUT', 419), ('KEY_ZOOMRESET', 420), ('KEY_WORDPROCESSOR', 421), ('KEY_EDITOR', 422), ('KEY_SPREADSHEET', 423), ('KEY_GRAPHICSEDITOR', 424), ('KEY_PRESENTATION', 425), ('KEY_DATABASE', 426), ('KEY_NEWS', 427), ('KEY_VOICEMAIL', 428), ('KEY_ADDRESSBOOK', 429), ('KEY_MESSENGER', 430), (['KEY_BRIGHTNESS_TOGGLE', 'KEY_DISPLAYTOGGLE'], 431), ('KEY_SPELLCHECK', 432), ('KEY_LOGOFF', 433), ('KEY_MEDIA_REPEAT', 439), ('KEY_IMAGES', 442), ('KEY_BUTTONCONFIG', 576), ('KEY_TASKMANAGER', 577), ('KEY_JOURNAL', 578), ('KEY_CONTROLPANEL', 579), ('KEY_APPSELECT', 580), ('KEY_SCREENSAVER', 581), ('KEY_VOICECOMMAND', 582), ('KEY_ASSISTANT', 583), ('KEY_BRIGHTNESS_MIN', 592), ('KEY_BRIGHTNESS_MAX', 593)], ('EV_REL', 2): [('REL_X', 0), ('REL_Y', 1), ('REL_HWHEEL', 6), ('REL_WHEEL', 8), ('REL_WHEEL_HI_RES', 11), ('REL_HWHEEL_HI_RES', 12)], ('EV_MSC', 4): [('MSC_SCAN', 4)]}
19.5739 DEBUG: pid 13207, injector.py, line 99, numlockx not found
19.5746 DEBUG: pid 13207, injector.py, line 495, Started consumer to inject to /dev/input/event6, fd 39
26.4285 SPAM: pid 13207, keycode_mapper.py, line 360, ((1, 272, 1)) ----------------- forwarding
26.5243 SPAM: pid 13207, keycode_mapper.py, line 295, ((1, 272, 0)) ----------------- forwarding release
28.4523 SPAM: pid 13207, keycode_mapper.py, line 355, ((1, 277, 1)) ----------------- maps to 3
28.5719 SPAM: pid 13207, keycode_mapper.py, line 291, ((1, 277, 0)) ----------------- releasing 3
28.9402 SPAM: pid 13207, keycode_mapper.py, line 355, ((1, 278, 1)) ----------------- maps to 4
29.0602 SPAM: pid 13207, keycode_mapper.py, line 291, ((1, 278, 0)) ----------------- releasing 4
29.4121 SPAM: pid 13207, keycode_mapper.py, line 355, ((1, 279, 1)) ----------------- maps to 5
29.5481 SPAM: pid 13207, keycode_mapper.py, line 291, ((1, 279, 0)) ----------------- releasing 5
30.7879 SPAM: pid 13207, keycode_mapper.py, line 355, ((1, 275, 1)) ----------------- maps to 2
30.8839 SPAM: pid 13207, keycode_mapper.py, line 291, ((1, 275, 0)) ----------------- releasing 2
31.0758 SPAM: pid 13207, keycode_mapper.py, line 355, ((1, 276, 1)) ----------------- maps to 9
31.1880 SPAM: pid 13207, keycode_mapper.py, line 291, ((1, 276, 0)) ----------------- releasing 9
31.3719 SPAM: pid 13207, keycode_mapper.py, line 355, ((2, 6, -1)) ------------------ maps to 11
31.4300 SPAM: pid 13207, keycode_mapper.py, line 291, ((2, 6, 0)) ------------------- releasing 11
31.8679 SPAM: pid 13207, keycode_mapper.py, line 355, ((2, 6, 1)) ------------------- maps to 10
31.9347 SPAM: pid 13207, keycode_mapper.py, line 291, ((2, 6, 0)) ------------------- releasing 10
34.5001 SPAM: pid 13207, keycode_mapper.py, line 360, ((1, 273, 1)) ----------------- forwarding
34.5878 SPAM: pid 13207, keycode_mapper.py, line 295, ((1, 273, 0)) ----------------- forwarding release
48.1946 SPAM: pid 13207, keycode_mapper.py, line 360, ((1, 272, 1)) ----------------- forwarding
48.2746 SPAM: pid 13207, keycode_mapper.py, line 295, ((1, 272, 0)) ----------------- forwarding release
48.2939 INFO: injector.py, line 547, Stopping injecting keycodes for device "ELECOM ELECOM TrackBall Mouse"
48.2946 DEBUG: pid 13207, injector.py, line 350, Received close signal
48.2949 DEBUG: pid 13207, injector.py, line 470, asyncio coroutines ended
48.2978 DEBUG: injector.py, line 99, numlockx not found
^CTraceback (most recent call last):
  File "/usr/bin/key-mapper-service", line 70, in <module>
    loop.run()
  File "/usr/lib/python3.9/site-packages/gi/overrides/GLib.py", line 497, in run
    super(MainLoop, self).run()
  File "/usr/lib64/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/usr/lib64/python3.9/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt
53.7506 INFO: daemon.py, line 219, Stopping all injections
53.7633 INFO: injector.py, line 547, Stopping injecting keycodes for device "ELECOM ELECOM TrackBall Mouse"
53.7699 DEBUG: injector.py, line 99, numlockx not found
`
I don't remember if I tried to press the buttons when I was running the debug mode. Tomorrow I'll install key-mapper on another computer and I'll tell you if I have the same problems with the latest version.

**Comment by sezanzeb** [comment]
I just pushed a fix. Can you verify that it works now?

**Comment by CarlosEkisde** [comment]
The upgrade seems to be working. It gets stuck for two or three seconds when I click to apply when on 0.6 I felt it was instant but then it's working again and it seems consistent. Thank you, for me it's solved. Close the issue if you consider appropriate.

**Comment by sezanzeb** [comment]
yeah there can be a gab between grabbing the device and injecting stuff.

Thanks for reporting!
