### ISSUE TITLE
[Feature Request] Add support for left key remapping

### ISSUE THREAD

**Issue by CarlosEkisde** [sezanzeb/key-mapper#37]
I've just noticed that key-mapper can't remap left button, it doesn't get detected on the correspondent box when you press it.

Being able to remap left button would be useful for the following use cases: 
- Models like Kensington Slimblade and Expert trackballs.
- Just for lefties on normal mices
- Using the left button as part of some key combinations.

Thanks in advance.

**Comment by sezanzeb** [comment]
I'll look into it later. It definitely makes sense, it just broke the UI when it was possible because clicking also interacts with it. I need to check if that is still the case and invest some time into finding a workaround if there are still problems.

**Comment by sezanzeb** [comment]
But basically you can write configs if you want that now

- https://github.com/sezanzeb/key-mapper/discussions/26
- https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md#configuration-files
- key for `"mapping"` is `"1,272,1"`
- name is `btn_left`

**Comment by dk-88** [comment]
I am using a Kensington slimblade and si also ran into this limitation. The middle and left mouse button can't be chorded using the UI.
For now I will edit dhe config.

**Comment by sezanzeb** [comment]
middle button should work. Does it work when editing the config? Middle button would be 274

**Comment by BachoSeven** [comment]
@sezanzeb I can confirm the Middle button works in the GUI; i.e. it is recognised by first left-clicking the entry to map and the pressing middle-click.

**Comment by sezanzeb** [comment]
pushed to main, mapping the left mouse button should work now.

if no other button is configured as left mouse button it will display a warning, pressing apply a second time will overwrite that warning.
