### ISSUE TITLE
add support for non-GUI

### ISSUE THREAD

**Issue by OrionRandD** [sezanzeb/key-mapper#4]
Could you add in your TODOs a support for ttys, non-GUI
environments?
Thx a lot

**Comment by sezanzeb** [comment]
Can do. Thanks for the request.

The daemon running in the background is a D-Bus server that loads .json configurations, so all that is needed for that would be a way to send matching messages to that daemon via a command.

Furthermore, the few calls to X/Wayland related stuff like `xmodmap -pke` need to be disabled or wrapped in try/catch statements.

So as far as I can tell, it wouldn't be much work.

**Comment by OrionRandD** [comment]
thx. Perhaps changing keyboard layouts in GUI and non-GUI/tty would be great as well.
Specially for languages like Portuguese/Brazilian Portuguese - ABNT2 layout - that require cedilla,
French and other languages with lots of accents and have been very difficult to configure in non-GUI environments and that require some hacks to do. Like so:
https://superuser.com/questions/1075992/cedilla-under-c-%C3%A7-in-us-international-with-dead-keys-keyboard-layout-in-linu
https://askubuntu.com/questions/363115/how-to-type-latin-small-letter-c-with-cedilla
https://www.linuxquestions.org/questions/slackware-14/unusual-ccedilla-in-us-international-with-dead-keys-keyboard-layout-for-pt_br-utf-8-location-in-kde-5-only-4175636787/

**Comment by sezanzeb** [comment]
I see.

You can also use `xmodmap -e "keycode  10 = ccedilla"` to put ç on your "1".

You can also try to bind it to some shift combination with `xmodmap -e "keycode  10 = 1 ccedilla"`

**Comment by sezanzeb** [comment]
key-mapper injects keycodes and not characters, so it's linux/xkb job to make something of it. There doesn't seem to be a keycode that writes a complete ccedilla, but with a macro it might work:

it depends on the keyboard layout how your macro has to look like, but for german layouts, a macro to write ccedilla would look like `m(key_rightalt, k(dead_acute)).k(c)`

**Comment by OrionRandD** [comment]
Yah. This issue about Brazilian layout ABNT-2 - the official keyboard in
Brazil - has a long history and they never fixed that out for using this
layout with us-intl keyboards. People get mad when they have to use this
keyboard with that BR layout. Specially when they buy laptops in USA...

**Comment by sezanzeb** [comment]
I have wrapped some x command stuff for better tty support. But there is no command to start and stop injection yet. You'll have to configure json configs and then start `key-mapper-service`, either automatically in e.g. .bashrc or with `&` to daemonize it.

**Comment by sezanzeb** [comment]
Here is some info on configs: https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md#configuration-files

**Comment by sezanzeb** [comment]
Added some more stuff for tty support in 0.4.0

**Comment by sezanzeb** [comment]
@OrionRandD on the xkb branch ccedilla works for me. Could you please try it and give me some feedback?
