### ISSUE TITLE
Packing via debian/rules

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/key-mapper#40]
To satisfy FTBFSIASW (https://ftp-master.debian.org/REJECT-FAQ.html). Apparently it should be possible to create .deb packages using `dpkg-buildpackage -us -uc`. scripts/build.sh would not be allowed

It is some sort of makefile, and I know nothing about those. I also seems quite troublesome to get it running like that. It would be nice if somebody who has done debian compliant deb packaging in the past could help out here.

**Comment by sezanzeb** [comment]
examples for other python packages:
- https://packages.ubuntu.com/hirsute/soundconverter
- https://packages.ubuntu.com/hirsute/lutris
- https://packages.ubuntu.com/hirsute/menulibre
- https://packages.ubuntu.com/hirsute/quodlibet

`debian.tar.xz` file on the right

**Comment by sezanzeb** [comment]
There are 3 people until now who said they would want this in official repos. I'd love to get it into the debian repo

**Comment by skitt** [comment]
Feel free to assign this to me, I’ve started working on it.

**Comment by sezanzeb** [comment]
Awesome! Thank you

So ideally we will first get a debian compliant build running, and then with version 1.0.0 request to get it into the repo (see https://mentors.debian.net/sponsors/)

**Comment by skitt** [comment]
OK, that works for me. There won’t be any need to find a sponsor, I’m an uploading DD so I can submit packages directly to the archive (or, more accurately, the “NEW queue” for review by the FTP team who are responsible for the archive overall).

**Comment by Blaimi** [comment]
summary of #82: The development of the debian-package for building via debian/rules has moved to [debian salsa](https://salsa.debian.org/python-team/packages/key-mapper). There is also a ITP-Report for debian: [#986918](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986918)

**Comment by sezanzeb** [comment]
1.0.0 released, I'm fine with putting that into the debian repo

**Comment by skitt** [comment]
Excellent, I’ll take care of that tomorrow.

**Comment by sezanzeb** [comment]
really amazing.

I committed the version bump after I made the release tag this time. Don't know if that makes any difference for you, just to let you know.

**Comment by skitt** [comment]
It’s in the NEW queue (waiting for review by the FTP team): https://ftp-master.debian.org/new/key-mapper_1.0.0-1.html

**Comment by sezanzeb** [comment]
@skitt, should changes since 1.0.0 be included there? key-mapper has internationalization now and the service was writing debug logs when it shouldn't https://github.com/sezanzeb/key-mapper/commit/b1b88a0a1fb6923bcba8cb301f5ba3de7bccbc6b

thanks! :)

**Comment by skitt** [comment]
@sezanzeb let’s wait for the current upload to be processed. In practice after the initial upload, packages are updated when new releases happen upstream ;-). When the 1.0.0-1 package goes in, I’ll update it to whatever is the latest release of key-mapper. (For bug fixes, I can add specific patches to the package, there’s no need to wait for an actual release. The debug log fix might qualify.)

**Comment by skitt** [comment]
`key-mapper` has just been accepted into Debian (for Debian 12): https://tracker.debian.org/news/1247771/accepted-key-mapper-100-1-source-all-into-unstable-unstable/

https://tracker.debian.org/pkg/key-mapper will be populated with more information as the package is processed.

**Comment by sezanzeb** [comment]
Thank you so much once more! This is a milestone for key-mapper and kinda for me as well

I guess we should close this issue then :)
