### ISSUE TITLE
Authentication method doens't work on main.

### ISSUE THREAD

**Issue by CarlosEkisde** [sezanzeb/key-mapper#43]
I'm on Fedora 33 Plasma 5.21. Now key-mapper from master doesn't show the graphical tool for authenticating. When running key-mapper-gtk-pkexec it shows a password prompt, but after entering the password it gives an error and key-mapper terminates

```
key-mapper-gtk-pkexec
==== AUTHENTICATING FOR keymapper ====
Authentication is required to discover and read devices.
Authenticating as: xxxxxx
Password: 
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
```

**Comment by sezanzeb** [comment]
try `pkexec mousepad`, same error?

**Comment by CarlosEkisde** [comment]
I'm closing here. It seems an issue with new plasma upgrade.
