### ISSUE TITLE
Can't create another remapping without saving and change profile first on main.

### ISSUE THREAD

**Issue by CarlosEkisde** [sezanzeb/key-mapper#44]
On main branch UI now seems to be a little buggy. The button "create new" doesn't show after remapping a button first and every time seems to be necessary to first save profile, change to another profile and then go back to the profile that I want to configure.

**Comment by sezanzeb** [comment]
You mean "new" I guess?

There is no logic for showing or hiding those 4 buttons implemented

**Comment by CarlosEkisde** [comment]
I don't know why but it's working right now

**Comment by sezanzeb** [comment]
or were you talking about the "click here" button?

**Comment by CarlosEkisde** [comment]
Yes, that button. After trying a few more times I can't replicate this issue anymore.

**Comment by sezanzeb** [comment]
I'm gonna put some extra checks into the function that does that stuff https://github.com/sezanzeb/key-mapper/blob/main/keymapper/gui/window.py#L267

**Comment by sezanzeb** [comment]
Pushed more thorough checking if an empty row should be added and more debug log if things go wrong. It also won't just stop checking if an inconsistency is found.
