### ISSUE TITLE
Tartarus v2 key button stuck/repeats (Manjaro, OpenRazer)

### ISSUE THREAD

**Issue by ArnoldDeRuiter** [sezanzeb/key-mapper#46]
I just installed key-mapper and it's everything I could've wanted, thank you!

However, I found that when mapping say the BTN_MIDDLE on my Tartarus v2 to control_l+v, it keeps both keys pressed. (So it keeps pasting my clipboard)
It seems as if 'is_key_up' is not triggered.

The specific behaviour is as follows:
I press BTN_MIDDLE on the Tartarus v2, it pastes my clipboard (control_l+v), and for let's say, 200-300ms that's it.
Then it just goes ahead and spam pastes the clipboard, non-stop, until I unplug the Tartarus v2.
After unplugging the Tartarus v2 it keeps pasting for a little while longer and then finally stops.

I'm not sure, with the short time I've looked at the code, specifically around keycode_mapper.py, if the issue/bug is with the code or my Manjaro/OpenRazer installation. (Both up-to-date as of this submission)

Other than that it works wonders and this is not a major issue for me. :+1:

**Comment by sezanzeb** [comment]
Which distro are you on? And which version of key-mapper? did you install from main or using the 0.6.1 deb?

run

```
sudo systemctl stop key-mapper
sudo key-mapper-service -d
```

now open the gui and start injecting. Press the button to reproduce the problem, then unplug your device or stop using the "Restore defaults" button.

Show me the produced log afterwards please.

**Comment by sezanzeb** [comment]
having openrazor installed shouldn't cause any problem. They are working on some remapping stuff based on injecting via evdev as well, but it's not merged yet https://github.com/openrazer/openrazer/pull/1124

**Comment by sezanzeb** [comment]
as a workaround, you can map `m(control_l, k(v))` to it. It will be executed only once and not held down while the key is pressed

**Comment by sezanzeb** [comment]
it's most likely fixed. Feel free to reopen if still reproducible
