### ISSUE TITLE
v0.7.0 using Key + Key vs macros

### ISSUE THREAD

**Issue by jim8989** [sezanzeb/key-mapper#47]
Ubuntu uses the super key and the page up or page down to scroll thru workspaces.  If I use the macro the scrolling works really nice. Ubuntu's keyboard mapping uses to scroll through the workspaces 'Super+Page Up or Super+Page Down' and xev reports the Page Up key = Prior and the Page Down key = Next.
The working macro looks like this:
REL_HWHEEL R		m(super_l, k(next))
REL_HWHEEL L		m(super_l, k(prior))

If I try using the new key + key syntax I don't get the same scrolling through the workspaces. 
REL_HWHEEL R		super_l + next
REL_HWHEEL L		super_l + prior
When I press  the mouse button (R)  one workspace is scrolled down, a slight pause, then the scrolling continues all the way to the last workspace and the scrolling stops working if the left or right button is pressed.  Am I using the syntax incorrectly?

Jim

**Comment by sezanzeb** [comment]
you did let go of your mouse button and it still just continued to scroll down?

you used the syntax correctly.

I fixed one problem for that syntax shortly after releasing 0.7.0, but I included that fix in the .deb file afterwards.

please run

```bash
sudo systemctl stop key-mapper
sudo key-mapper-service -d
```

and open the gui, apply the mapping and reproduce the problem. Then share those logs with me please.

**Comment by sezanzeb** [comment]
possibly related to https://github.com/sezanzeb/key-mapper/issues/46

**Comment by jim8989** [comment]
[Key-mapper_log.txt](https://github.com/sezanzeb/key-mapper/files/6039200/Key-mapper_log.txt)

**Comment by sezanzeb** [comment]
this doesn't contain debug logs unfortunately. I usually need those but they are just too verbose to log them by default.

**Comment by jim8989** [comment]
I just pushed the mouse button once.  When I use the macro every time I press and hold the mouse button I scroll to the next workspace and there is a pause, then I scroll down to the next workspace and pause.  This continues until I reach the last workspace.

Using the key+key syntax I press the mouse button and as I scroll to the next workspace I release the button. Upon reaching the next workspace the is the normal pause then a fast scroll to the end of the workspaces with my finger off of the button.
[Key-mapper_log.txt](https://github.com/sezanzeb/key-mapper/files/6039217/Key-mapper_log.txt)

**Comment by sezanzeb** [comment]
The file you linked contains the same logs again. With debug logs I mean `-d`, so it's necessary for you to execute the commands below:

```
sudo systemctl stop key-mapper
sudo key-mapper-service -d
```

and then reproduce it, i.e. push the button once while the above command is running. Those logs will contain much more information that I need to debug the problem

**Comment by jim8989** [comment]
I read issue 46 and it looks like you have a work around.  Your software works really well when I use the macro I originally used.  I just sent an issue because because I tried a key+key syntax.  I have no problem enjoying your software using a macro.  If you want to use me as a test subject down the road let me know.  I'll go back to using the macro statements.

Jim

**Comment by sezanzeb** [comment]
Can you try to download the .deb file again and install it? I just noticed the commit hash in your log isn't quite up to date

**Comment by jim8989** [comment]
Installed the new 0.7.0 .deb package and it looks like you fixed the problem. I'll update my main Laptop and add the key + key syntax to verify that it's working well.  Nice fast fix, sure do like the package you wrote.

Jim
