### ISSUE TITLE
Suggestion: Any plans on adding focus dependant configurations ? 

### ISSUE THREAD

**Issue by Werner1201** [sezanzeb/key-mapper#50]
I firstly want to congratulate you with your project, and for the commitent with it. That said, I was wandering if it's on the plans of the project of adding a focus window option, where if there's x window focused at the moment, change certain binding to another ones. It would be a very cool addition that I don't see in any other key binding apps on Linux. I wait for your response if it's possible or there's any limitation on the X Org or the DE way of dealing with focused windows.

**Comment by sezanzeb** [comment]
Unfortunately there are limitations in wayland https://github.com/sezanzeb/key-mapper/discussions/20
