### ISSUE TITLE
20.04 internal error

### ISSUE THREAD

**Issue by jim8989** [sezanzeb/key-mapper#53]
I installed Ubuntu 20.04 and recently and I'm getting a system error shortly after logging in and when I look at the error it references Key-mapper.  The version I'm running is 0.7.0 which I downloaded on 2/25/21. I could try not auto starting your program and starting it after a few minutes after I log in.  Do you have any other tests you'd like me to try.  I started installing 20.04 and several programs about 7-8 days ago.  Key-Mapper was one of the first ones installed and I didn't start getting this error until a 3-4 days ago.  The errors started sporadically but the last couple days it occurs every time I boot my computer and a few minutes after I log in and after I close the error I don't get another one the rest of the time my laptop is on. 

![Ubuntu_005](https://user-images.githubusercontent.com/45720776/110221155-2cfb7700-7e90-11eb-86ec-61aa3d7b0356.png)

**Comment by sezanzeb** [comment]
Please post the output of

`key-mapper-control --command hello`

**Comment by jim8989** [comment]
key-mapper-control --command hello
Loaded config from "/home/jb/.config/key-mapper/config.json"
Daemon answered with "hello"

systemctl status key-mapper
● key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/lib/systemd/system/key-mapper.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-03-06 15:08:58 CST; 1h 51min ago
   Main PID: 1008 (key-mapper-serv)
      Tasks: 4 (limit: 9388)
     Memory: 26.0M
     CGroup: /system.slice/key-mapper.service
             ├─1008 /usr/bin/python3 /usr/bin/key-mapper-service
             └─2883 /usr/bin/python3 /usr/bin/key-mapper-service

Mar 06 15:09:21 S76-Kudu key-mapper-service[1008]: Loaded config from "/home/jb/.config/key-mapper/config.json"
Mar 06 15:09:21 S76-Kudu key-mapper-service[1008]: Stopping all injections
Mar 06 15:09:22 S76-Kudu key-mapper-service[1008]: Loaded config from "/home/jb/.config/key-mapper/config.json"
Mar 06 15:09:22 S76-Kudu key-mapper-service[1008]: Autoloading for all devices
Mar 06 15:09:23 S76-Kudu key-mapper-service[1008]: Found "Video Bus", "SynPS/2 Synaptics TouchPad", "Logitech USB Receiver", "AT Translated Set 2 keyboard", "Sleep Button"
Mar 06 15:09:23 S76-Kudu key-mapper-service[1008]: Autoloading "Logitech USB Receiver"
Mar 06 15:09:23 S76-Kudu key-mapper-service[1008]: Loading preset from "/home/jb/.config/key-mapper/presets/Logitech USB Receiver/super + Workspace Scrolling.json"
Mar 06 15:09:23 S76-Kudu key-mapper-service[2883]: Starting injecting the mapping for "Logitech USB Receiver"
Mar 06 16:58:39 S76-Kudu key-mapper-service[1008]: Loaded config from "/home/jb/.config/key-mapper/config.json"
Mar 06 16:58:39 S76-Kudu key-mapper-service[1008]: Received "hello" from client

**Comment by sezanzeb** [comment]
and it starts mapping your device? or is that broken?

**Comment by sezanzeb** [comment]
I also had my fair share of annoyances with apport. "The reporting errors program (Apport) is known to complain about stupid things" (https://askubuntu.com/a/951654)

And It makes no sense at all. my only usage of bus.get is catching GError exceptions. It looks like the tool is working just fine

**Comment by jim8989** [comment]
I downloaded the .deb file 0.7.0 several days ago, reinstalled the package  and I'm still getting an error window shortly after logging in.  The mouse is mapped properly, I'm just getting the error window once.

**Comment by sezanzeb** [comment]
install from source for that (by executing the commands in https://github.com/sezanzeb/key-mapper#ubuntudebian) or ignore the error.

usually the release file doesn't change once it has been created.

It will be part of then next release, possibly next weekend.

**Comment by sezanzeb** [comment]
the 0.7.1 release deb is available now
