### ISSUE TITLE
Automatic reapplying mappings on device reconnect

### ISSUE THREAD

**Issue by wodzborsuk** [sezanzeb/key-mapper#57]
Hello!

When I unplug and "replug" a device that has a set mapping I need to manually open key-mapper and click apply on the custom mapping for said device. Is it possible that this would happen automatically?

**Comment by sezanzeb** [comment]
Do you have "Autoload" checked?

**Comment by wodzborsuk** [comment]
auto-load is checked and it works on boot perfectly. 
I just checked and the version is 0.6.0 so i'll check on 0.7.0 and i'll let you know what happens.

**Comment by sezanzeb** [comment]
reopen if it still doesn't work with 0.7.0
