### ISSUE TITLE
Super Key

### ISSUE THREAD

**Issue by swt83** [sezanzeb/key-mapper#58]
I'm using an Apple keyboard and I'm unable to bind the left Super key.  The right Super key will bind, oddly.  I hit "click here" for the button I want to bind, but when I hit the left Super key it won't register.  It looks like the only button that won't work.

EDIT: I got this working, it was some kind of conflict with Tweaks.  My only remaining issue is sometimes the all my keys wig out and nothing works, even my mouse, and I have to log out and log back in and then it's fine.

**Comment by sezanzeb** [comment]
with "wig out" you mean "stop working"?

you are applying your mapping to your keyboard and then the mouse stops working? That's incredible. How do you log out when all of your devices stop working?

**Comment by sezanzeb** [comment]
When using the left super key on your keyboard, does the application lose its focus? As a workaround you can always also modify the configuration files instead: https://github.com/sezanzeb/key-mapper/discussions/26

**Comment by swt83** [comment]
You're asking me good questions, I don't know how I was able to log out.  The inability to bind left Super had to do with Gnome Tweaks settings that were also changing keybinds.  When I turned off all the Tweaks keyboard settings then Keymapper started working properly.  But after creating my binds in Keymapper all my buttons went haywire and I had to relog.  But it's all working perfectly now.
