### ISSUE TITLE
Razer basilisk V2 key not recognized "Razer Hypershift"

### ISSUE THREAD

**Issue by Amdarin** [sezanzeb/key-mapper#60]
Dear all,

I have been trying the Razer Basilsik V2 with the software and I found the key "Razer Hypershift" is not recognized when you pressing it to bind the keys into the software.

If you need any debugger output I can get it.

![BasiliskV2](https://user-images.githubusercontent.com/47058310/111159133-11335780-8599-11eb-96e2-0a9e6aece238.jpg)

**Comment by sezanzeb** [comment]
It seems the hypershift button modifies how the mouse reports events, which means no event for that particular button will ever reach the computer.

You can verify that by running `sudo evtest`. If pressing the hypershift button causes an event to be displayed, it should be possible to map it. If not, there is nothing key-mapper can do about it unfortunately.

**Comment by Amdarin** [comment]
Hi sezanzeb.

I attach the screenshot of evtest and the file with the output selecting one of the options.
![Imagen1](https://user-images.githubusercontent.com/47058310/111299637-78f8a980-8650-11eb-9231-45e4d53675f9.png)
[salida.txt](https://github.com/sezanzeb/key-mapper/files/6148409/salida.txt)

**Comment by sezanzeb** [comment]
so the hypershift button never caused an event to be written?

**Comment by Amdarin** [comment]
Yes, previously in windows I set up a combination of keys pressing Razer Hypershift + left click or Razer Hypershift + right click and when I tried in this way there is an output, but pressing Hypershift buttn alone not show any output. I going to gather that output to show you as soon as possible.

**Comment by sezanzeb** [comment]
in windows using some razer software? It probably stores that configuration on the mouse via the firmware

**Comment by sezanzeb** [comment]
feel free to reopen if you observed an event in evtest for that single isolated button

**Comment by Amdarin** [comment]
Hi.

So sorry for the delay. I have tried to change the profile. As you can see in the screenshot it has an event. I choose the profile pushing a button below in the same mouse and here you have the event.
![Ima1](https://user-images.githubusercontent.com/47058310/111616466-36ff6d00-87e2-11eb-9cb9-09d72ccbfe67.png)
![Ima2](https://user-images.githubusercontent.com/47058310/111616475-38309a00-87e2-11eb-8676-63ed180009ea.png)

**Comment by sezanzeb** [comment]
so you have a different profile loaded in the device firmware now? Does key-mapper work with that, does it show RIGHTCTRL in the gui when attempting to map that button?

**Comment by Amdarin** [comment]
Hi again.

Yes it works, I have to try different combinations example. Hypershift + M button or Hypershift + Left click or Right click. I will feedback soon.

Regards

**Comment by sezanzeb** [comment]
jo, any update? Can I close those two issues?

**Comment by Amdarin** [comment]
Yes of course. You can close both if there is anything more I'm gonna open a new one.
