### ISSUE TITLE
Feature: Duplicate Preset

### ISSUE THREAD

**Issue by JonasLoos** [sezanzeb/key-mapper#61]
It would be nice to be able to duplicate presets, so one wouldn't have to enter everything again, if the new preset should only have slight changes.

It could be implemented as a button next to `new`.  A disadvantage might be that it could become too clustered.

**Comment by sezanzeb** [comment]
Good idea! How about holding ctrl while clicking `new`, that wouldn't require a new button

**Comment by JonasLoos** [comment]
That sounds good. Although a tooltip or something similar would then be necessary for users to find the action

**Comment by sezanzeb** [comment]
pushed to main, please try it out. I will release it as part of 0.7.1 afterwards

**Comment by JonasLoos** [comment]
it works - awesome :D
