### ISSUE TITLE
Hypershift button for mouse Razer Basilisk V2

### ISSUE THREAD

**Issue by Amdarin** [sezanzeb/key-mapper#64]
Hi,
Previously we was talking about the Hypershift button. And there is an event as you can see en in the screenshot. I choose the event10 and pushing only the hypershift button. Clarify there is a small button below on the mouse which have three profiles. Let me know if you have something more.

![Ima1](https://user-images.githubusercontent.com/47058310/111617035-e8060780-87e2-11eb-98d4-ddfd3adf5de4.png)
![Ima2](https://user-images.githubusercontent.com/47058310/111617041-e9373480-87e2-11eb-952e-f0df2463158c.png)

**Comment by sezanzeb** [comment]
> Does key-mapper work with that, does it show RIGHTCTRL in the gui when attempting to map that button?

**Comment by sezanzeb** [comment]
see https://github.com/sezanzeb/key-mapper/issues/60
