### ISSUE TITLE
Some UI suggestions

### ISSUE THREAD

**Issue by JonasLoos** [sezanzeb/key-mapper#65]
just some ideas that might improve the ui (or the app in general):
* [x] add an about popup
* [ ] add keyboard shortcuts and a keyboard shortcuts popup
* [x] automatically save then applying a preset
* [x] disable save button if nothing was changed
* [x] maybe remove the save-button altogether and save on every change
* [x] confirm when deleting a non-empty preset
* [x] don't copy the name of the previously selected preset when creating a new one
* [ ] hide the rename field behind a button (less confusing)
* [ ] mark the preset with Autoload enabled in the preset list (maybe with a `*`)
* [x] if possible add icons in the Device list before the name indicating the type of the device (e.g. 🎮, ⌨,🖱)

**Comment by sezanzeb** [comment]
> don't copy the name of the previously selected preset when creating a new one

yeah that was a bug I introduced in a previous change. Fixed it and added a test.

Good ideas, thanks. I think you are right about removing the save button altogether

**Comment by JonasLoos** [comment]
> Good ideas, thanks. I think you are right about removing the save button altogether. Instead I could add a "copy" button, which 
currently only works with a key combination due to space constraints.

Thanks. Yes, that sounds good to me.

> Where would you place the button or icon to open the about popup? On the top right maybe next to "Restore Defaults" as a question mark icon?

Usually it's hidden in some menu which can be opened from the title bar, but if it's only the about popup, a menu doesn't make much sense. Maybe just a `?` button in the title bar would be an option.

gnome-disks | nautilus | custom app
-|-|-
![image](https://user-images.githubusercontent.com/33965649/111764865-f8ca8200-88a3-11eb-8b3b-68c81ccd01cc.png) | ![image](https://user-images.githubusercontent.com/33965649/111764902-07189e00-88a4-11eb-8da6-48f786db9450.png) | ![image](https://user-images.githubusercontent.com/33965649/111768242-fa964480-88a7-11eb-9f27-5fbf9217b780.png)

**Comment by sezanzeb** [comment]
It would be easy to add it there:

![image](https://user-images.githubusercontent.com/28510156/111847104-7b852880-8908-11eb-883b-a858d4611ed6.png)

Putting it into the title bar next to the window control requires gtks special header bar, which needs a bit of css to ensure it works with the device selection and bla blub, it's just a bit of extra struggle that I'm not very interested in right now.

**Comment by JonasLoos** [comment]
I didn't know it requires extra css, or do you think about putting the whole device selection into the title bar (similar to mode selection in gnome-calculator)?
<img src=https://user-images.githubusercontent.com/33965649/111849199-4e874480-890d-11eb-90c9-122fef5ca581.png width="400">

---

Personally I would slightly prefer an icon in the title bar, but if it's really some extra struggle, I agree, it wouldn't be worth it.

**Comment by sezanzeb** [comment]
It doesn't really require css, but it won't look good with the existing stuff without some. It can still be changed later on anyways

**Comment by sezanzeb** [comment]
which keyboard shortcuts would you like to see?

**Comment by JonasLoos** [comment]
some ideas:

* `ctrl`+`s` for save (or apply if it's autosaved)
* `ctrl`+`r` for restore defaults
* `del` for delete
* `ctrl`+`?` for keyboard shortcuts overview (if available)
* `alt`+{`1`,`2`,...} for device selection (or maybe preset selection)

But I think that keyboard shortcuts are not very important, as most people probably won't use key-mapper enough to remember them.

**Comment by sezanzeb** [comment]
`del` to delete a row if one is selected, or the whole preset if not (which would show the confirmation dialog first)

`shift + del` is currently restore defaults

**Comment by JonasLoos** [comment]
I thought about using `del` for deleting the whole preset, but maybe it's better for the rows and use e.g. `ctrl`+`del` for deleting the preset.

Keeping `shift`+`del` for restore defaults, when adding `del` for deleting, might be confusing

**Comment by sezanzeb** [comment]
pushed some changes to main

**Comment by JonasLoos** [comment]
Nice, especially the usage info seems helpful!

some little things I noted:
* about window
  * it usually contains also info about the author and the license 
  * it is usually closable with `esc`
* "confirm delete" popup 
  * it doesn't spawn in the center of the app
  * it might be helpful, if it contained the name of the preset
  * the `delete` and `go back` buttons are usually the other way around, I think *
* it would be nice if pressing enter in the rename field triggers the `save name` button

\* :
<img src=https://user-images.githubusercontent.com/33965649/111908824-024a1a80-8a5b-11eb-92be-5ad67dcbb0b8.png width=400px>

---

Please take all those suggestions as spontaneous ideas and nothing more :sweat_smile:
And generally about key-mapper: good work!

**Comment by sezanzeb** [comment]
Thanks!

your points are absolutely valid, I'll (try to) implement all of your new suggestions.

**Comment by sezanzeb** [comment]
> the delete and go back buttons are usually the other way around, I think *

yes:

> the affirmative button at the far right, and the cancel button left of it

(https://developer.gnome.org/gtk3/stable/GtkDialog.html)

**Comment by sezanzeb** [comment]
pushed new changes. I also changed some distances to match the gnome guidelines https://developer.gnome.org/hig/stable/visual-layout.html.en

**Comment by sezanzeb** [comment]
does this look better? Pushed those changes to the `ui-improvements-3` branch

![image](https://user-images.githubusercontent.com/28510156/111966446-370baf80-8af7-11eb-939b-bdee94072cc8.png)

![image](https://user-images.githubusercontent.com/28510156/111966504-47238f00-8af7-11eb-9218-9cadaa7b401d.png)

**Comment by JonasLoos** [comment]
I think I slightly prefer `ui-improvements-3` as it looks a bit cleaner

**Comment by sezanzeb** [comment]
added icons for the devices
