### ISSUE TITLE
Add ability to reserve key as modifier/disable it completely

### ISSUE THREAD

**Issue by mmazur** [sezanzeb/key-mapper#68]
(This is slightly related to issue #49, but the goal is the opposite.)

Hi, my [keyboard config](https://github.com/mmazur/caps-madness-keyboard) is based around using the caps lock as a modifier. E.g. caps+hjkl is arrow keys.

However, this working is dependent on reserving the caps key as a modifier and disabling it's built–in functionality.

As a stop–gap I've assigned caps to `nosymbol`, but based on previous experience, I'm expecting to eventually stumble upon an app that will misbehave because of this.

Please add the ability to basically block a key completely ("IGNORE" mapping?), so that it sends no events ever (but does not prevent key combos based on it from working).

**Comment by mmazur** [comment]
Hmm, I'm thinking IGNORE and MODIFIER should be separate assignments. There are behaviors that are specific to modifier keys that, even if not implemented right now, would be nice to have an option of adding at some point without worrying about compatibility.

For a concrete example – if you keep pressing A key and then tap Shift a few times for a bit, you get basically aaaaaAAAAAAaaaaaAAAAaaaaa because tapping a modifier key does not interfere with the key being modified.

Trying the same exercise with e.g. j and caps+j should result in jjjjjjjjjjleftleftleftleftleftjjjjjjjjjleftleftleftjjjjjjjjjjjjj, but it does not. Making it clear in the config that I want Caps to be treated as a modifier key would make it possible to implement the proper bahavior.

**Comment by sezanzeb** [comment]
> You can disable KP1 by mapping it to disable

(https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md)

**Comment by mmazur** [comment]
Heh, a UI discoverability issue. I was searching for "no key" and "ignore", didn't occur to me to search for "disable". Maybe those two should filter down to "disable" so people have an easier time finding them.

The comment holds though – even with "disable", the key does not fully act like other modifier keys. I'm not sure that's a problem though, I can't come up with a realistic scenario. If I do hit one, I'll write a separate issue, otherwise it's likely not worth the bother.
