### ISSUE TITLE
Keys no longer detected in UI after first "apply"

### ISSUE THREAD

**Issue by mmazur** [sezanzeb/key-mapper#69]
(Not sure if this is a side effect of the #66 fix or a separate issue.)

I'm running `sudo key-mapper-gtk -d`.

First time I run it, I'm able to add new key combos and they get detected correctly.

But after the first time I run "Apply", I can no longer detect keys in the UI. I press them, I see them in the logs, but that's it, they don't show up in the UI, therefore to add a new key combo, I need to restart key-mapper-gtk.

One possible hint I've noticed is that when switching between windows, when focus is back to key-mapper-gtk, I get "INFO: window.py, line 346, Cannot change keycodes while injecting". It still thinks it's injecting, hence the problems?

**Comment by sezanzeb** [comment]
Does this appear when attempting to edit?

![image](https://user-images.githubusercontent.com/28510156/111912548-6f18e100-8a6a-11eb-91a5-d1b6485b1668.png)

> To change the mapping, you need to use the "Restore Defaults" button, so that the application can read the original keycode. It would otherwise be invisible since the daemon maps it independently of the GUI.

(https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md)

**Comment by mmazur** [comment]
Yup, that was it. I guess UI could be clearer on what's happening.
