### ISSUE TITLE
Hi, I did some work on another project you might find helpful

### ISSUE THREAD

**Issue by DanielJoyce** [sezanzeb/key-mapper#70]
https://github.com/philipl/evdevremapkeys/pull/27/files

* How to build a static binary from python code
* How to run as a Systemd User service 
* Configuring your tablet properly if not support OOTB on linux, using uaccess in udev rules.

**Comment by sezanzeb** [comment]
> How to build a static binary from python code

What would be the benefit?

> How to run as a Systemd User service

The service needs to be a root daemon to access the existing devices, which is being started via systemd

> Configuring your tablet properly if not support OOTB on linux, using uaccess in udev rules.
> The magic is the `TAG+="uaccess` line which means that the device will be created with permissions
to be accessible to the currently logged in user.

This hasn't been an issue so far
