### ISSUE TITLE
i18n support missing

### ISSUE THREAD

**Issue by jose1711** [sezanzeb/key-mapper#71]
This is a very useful utility, yet support for translation is missing.

**Comment by sezanzeb** [comment]
after version 1.0.0 when stuff probably doesn't change much anymore I would be fine with adding that

**Comment by jose1711** [comment]
Bumping as version 1.0 exists for a while now and I haven't seen any drastic changes recently.

**Comment by sezanzeb** [comment]
Feel free to make a contribution and add translation files yourself :) I'm busy at the moment

**Comment by jose1711** [comment]
> Feel free to make a contribution and add translation files yourself :) I'm busy at the moment

I can start to translate the `.glade` file generated by `xgettext` but for the actual PR I would need to know where to include it. Some architectural changes needs to be done first (directory containing the `.po` files, `gettext`/`locale` stuff etc)

**Comment by sezanzeb** [comment]
thank!

Just create another root level directory called "po", like [soundconverter](https://github.com/kassoulet/soundconverter) and [menulibre](https://github.com/bluesabre/menulibre).

Here is some example code for gettext from soundconverter: https://github.com/kassoulet/soundconverter/blob/py3k/soundconverter/interface/ui.py

But I didn't set that up so I don't know how it really works. DistUtilsExtra that is used there compiles po files automatically, here is some result after a quick search how it can work: https://stackoverflow.com/a/38974981

**Comment by jose1711** [comment]
FWIW I was planning to do a `.pot` able to refresh the translations from code but failed miserably. Here's how I created it:
```
xgettext -k --keyword=translatable --sort-output -o po/key-mapper.pot data/key-mapper.glade
xgettext --keyword=_ -L Python --sort-output -jo po/key-mapper.pot bin/key-mapper-gtk
```

**Comment by sezanzeb** [comment]
Thanks for your work. If the commands will be relevant in the future, please add them to development.md: https://github.com/sezanzeb/key-mapper/blob/main/readme/development.md
