### ISSUE TITLE
Ignore (filter out) YubiKey and similar devices

### ISSUE THREAD

**Issue by jose1711** [sezanzeb/key-mapper#78]
Nothing big but I don't think YubiKey or similar hw devices should be listed in Device section of `key-mapper` program. Configuring keys for these keys does not really make sense as they usually generate just random key-presses when activated.

![obrázok](https://user-images.githubusercontent.com/1406222/113706201-b3e57e80-96de-11eb-919e-cbc307fcbd85.png)

**Comment by sezanzeb** [comment]
thanks. pushed to main

**Comment by jose1711** [comment]
Thank you, my Yubikey is not matched however. `device.info.vendor` resolves to 4176 while there is `'Yubico'` in the `DENYLIST`.

**Comment by sezanzeb** [comment]
try again please

**Comment by jose1711** [comment]
Thank you, now it works.
