### ISSUE TITLE
Uninstalling when setup.py was used?

### ISSUE THREAD

**Issue by mauritzn** [sezanzeb/key-mapper#81]
Currently the `setup.py` script only has a install script, would it be possible to get an uninstall script as well? Since during all the testing with the xkb branch I used `setup.py` to be able to quickly install different version, but now I'm left with an install that doesn't have the regular uninstall options like `apt` or `pip`.

Or is there already an uninstall script somewhere in the project? I don't have a problem doing it manually, so this is more an issue I bring up if other users need it in the future.

Currently doing a `pip uninstall` of key-mapper does remove it from Python's `dist-packages`, but leaves behind the .desktop file and other files and still allows for the running of the `key-mapper-gtk` command, even though it now throws an error due to the missing `dist-packages` files.

The reason I'm uninstalling the version installed using `setup.py` is to move over to the .deb version again.

**Comment by sezanzeb** [comment]
setup.py doesn't offer that, which is why I removed that from the readme.

Can you try https://askubuntu.com/a/56764?

If that doesn't work, what I usually did in that case is

```bash
cd /usr
sudo find . -iname "*key*mapper*" -exec rm {} -r \;
```

If you remove the `-exec` param you can see which files and folders are about to be removed.

good luck.
