### ISSUE TITLE
Framedrops when binding regular keys to LeftCtrl/CapsLock etc.

### ISSUE THREAD

**Issue by ArnoldDeRuiter** [sezanzeb/key-mapper#89]
I'm experiencing framedrops (in Minecraft, both Vanilla and Sodium) when I press a key ('3' or 'k' for example) that is mapped to LeftCtrl or CapsLock in key-mapper.

I've tried switching between X11 and Wayland, and while sometimes the problem goes away when switching, it isn't consistant.

Running Manjaro Linux with Gnome on kernel 5.10 using Key-mapper 0.8.1 2767391.

When I bind '3' or 'k' to say ''4 or 'l', the issue is non existent. Only on special keys like Ctrl, CapsLock etc.

Is there a log I could share, or something I could try on my end to resolve this?

Edit:
While it appears as a lockup/framedrop on my screen.
A recording with say OBS doesn't show this, at all.
I'm using a AMD GPU and CPU, fwiw.

**Comment by sezanzeb** [comment]
As mentioned in the [issue template](https://github.com/sezanzeb/key-mapper/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) logs to share are generated via `sudo systemctl stop key-mapper && key-mapper-gtk -d`

**Comment by sezanzeb** [comment]
You could try a different environment instead of gnome, do you have the same issue there? For example xfce

**Comment by sezanzeb** [comment]
Feel free to reopen once you have new information
