### ISSUE TITLE
Dark theme no longer loading

### ISSUE THREAD

**Issue by amadeusp** [sezanzeb/key-mapper#9]
I am on Manjaro 20.2 GNOME running the 5.9.1-1-rt19-MANJARO kernel.

I use key-mapper-git 0.4.0-1 from the AUR.

The version I had installed prior to 0.4.0-1 (unfortunately I don't remember which version that was exactly) was respecting the dark theme I am using (Prof-Gnome-Dark-3.6) and in consequence rendered its UI in dark mode. The new version 0.4.0-1 does render with a bright theme which I consider a bug. :)

**Comment by sezanzeb** [comment]
I just tried out the prof-gnome-dark theme (https://www.pling.com/s/Gnome/p/1334194/) and it's dark.

**Comment by amadeusp** [comment]
This is how it looks: https://www.dropbox.com/s/v6gqjhrhm6fmhm4/20201227-bright-theme.png?dl=0 No, restarting app or machine does not help.

**Comment by sezanzeb** [comment]
I just tried it on a computer with Gnome, installed all 4 theme variants and I still can't reproduce it.

**Comment by amadeusp** [comment]
Any idea what I could do to track this down? I just reinstalled the themes and also made a video as well: https://www.dropbox.com/s/8clz695jkd041fh/20201227-screencapture.mp4?dl=0

**Comment by sezanzeb** [comment]
what happens when you select, for eample, the matcha theme?

**Comment by sezanzeb** [comment]
check if, for some strange reason, something wrote stuff into `/usr/share/applications/key-mapper.desktop` that changes the theme. It should look like https://github.com/sezanzeb/key-mapper/blob/main/data/key-mapper.desktop

try to start it from a terminal with `sudo key-mapper-gtk` and see if it looks any different

**Comment by amadeusp** [comment]
Interesting, it works with Matcha.
`/usr/share/applications/key-mapper.desktop` looks fine.
It does not make any difference when started from the Terminal (not with `sudo key-mapper-gtk` and not with `key-mapper-gtk-pkexec`).

**Comment by sezanzeb** [comment]
No idea unfortunatelly

**Comment by sezanzeb** [comment]
try `sudo rm /usr/share/key-mapper/style.css` and start it again. I absolutely doubt this is doing anything, but it's the only style related thing I changed previously

**Comment by amadeusp** [comment]
Does not help, unfortunately. But I think this can be ignored. It seems to be something on my end. Thanks anyways!
