### ISSUE TITLE
Unable to configure devices with the same name independently

### ISSUE THREAD

**Issue by jose1711** [sezanzeb/key-mapper#93]
I have two wireless SpeedLink gamepads - each has its own USB receiver. In the output of `evtest` I can see both of them.
```
$ evtest 2>&1|grep SPEED
/dev/input/event5:	SPEEDLINK TORID
/dev/input/event24:	SPEEDLINK TORID
```
`key-mapper` is only showing single `SPEEDLINK TORID` entry receiving events from either controllers. This prevents from configuring them separately.

**Comment by sezanzeb** [comment]
Please run

```py
import evdev
for path in evdev.list_devices():
     device = evdev.InputDevice(path)
     print(device.name, device.uniq)
```

to see if uniq has to correct uniqueness for this. I don't have two devices of the same model at home

**Comment by jose1711** [comment]
`device.uniq` seems to be empty string for all detected devices. hmm..
```
>>> import evdev
>>> for path in evdev.list_devices():
...   device = evdev.InputDevice(path)
...   print(device.name, device.uniq)
... 
Microsoft X-Box 360 pad 
SPEEDLINK TORID 
Microsoft X-Box 360 pad 
..
HDA NVidia HDMI/DP,pcm=3 
SPEEDLINK TORID 
..
PC Speaker 
Eee PC WMI hotkeys 
Power Button 
Power Button 
```

**Comment by sezanzeb** [comment]
oh. Then maybe there is more luck with splitting device.phys, which can be empty as well though.

```
sudo python3
import evdev
for path in evdev.list_devices():
     device = evdev.InputDevice(path)
     print(device.name, device.phys)
```

**Comment by jose1711** [comment]
Yeah, that looks promising:
```
>>> import evdev
>>> for path in evdev.list_devices():
...   device = evdev.InputDevice(path)
...   if 'SPEEDLINK' not in device.name: continue
...   print(device.name, device.phys)
... 
SPEEDLINK TORID usb-0000:0c:00.3-3.1/input0
SPEEDLINK TORID usb-0000:0c:00.3-4/input0
>>> 
```

**Comment by sezanzeb** [comment]
Please try the "getdevices-duplicate-2" branch.

It has unittests already

**Comment by jose1711** [comment]
Thank you for your pro-support, tested in Broforce and it works nicely.

**Comment by sezanzeb** [comment]
nice. I'll continue working a bit on improving the architecture in that regard though and will let you know once it is in main

**Comment by sezanzeb** [comment]
No I think there is an issue

Will it store the preset for the second device in a different location? i.e. do you have two different sets of presets for each one of them?

**Comment by jose1711** [comment]
I get two separate files:
```
find .config/key-mapper/presets/SPEEDLINK\ TORID* -type f -ls
 90048293      4 -rw-------   1 jose     users         278 apr 13 23:32 .config/key-mapper/presets/SPEEDLINK\ TORID/move\ or\ die.json
 50860257      4 -rw-------   1 jose     users         191 apr 13 23:33 .config/key-mapper/presets/SPEEDLINK\ TORID\ 2/move_or_die.json
```

**Comment by sezanzeb** [comment]
Yeah, I'll be refactoring quite some stuff in that regard because the data structure and how things are being indexed is getting ridiculous. Will take a little bit more time

**Comment by sezanzeb** [comment]
I didn't fix the issue yet, but made a lot of changes that I would love to get tested by somebody else as well.

Please install the latest changes on the getdevices-duplicate-2 branch.

**Comment by jose1711** [comment]
> I didn't fix the issue yet

Sorry, which issue? I mean.. I was already getting two separate files per each device which I think is the way it's supposed to work. Or am I missing something?

**Comment by sezanzeb** [comment]
If you got two keyboards of the same type and configure two presets on day 1, and connect only one of them on day 2, the gui will only list one of the presets

Instead what I want to do is show all of them. Since they fit the device

**Comment by jose1711** [comment]
Thank you, that makes perfect sense. Will try to test in the following days.

**Comment by sezanzeb** [comment]
I'm finished with my work on that branch, I expect it to correctly handle devices of the same model now

does it work for you?

**Comment by jose1711** [comment]
Sorry, did not have a chance to test it yet and I am traveling during weekend. I suggest you push to main and if there are any issues I will reopen.
