### ISSUE TITLE
Key-Mapper Settings Not Persistent

### ISSUE THREAD

**Issue by reidellawfirm** [sezanzeb/key-mapper#94]
I am using Manjaro with Gnome 40.0 and Wayland. I am not able to get Key-Mapper to retain settings after a restart or after the computer sleeps. Any guidance on what I can try to maintain the Key-Mapper settings persistently on restarts etc.?

**Comment by sezanzeb** [comment]
you have checked the "Autoload" switch, right?

**Comment by reidellawfirm** [comment]
I did not, will try that. Wasn't sure what the function of that button was so I never used it. 

Looks like it is functioning persistently now:

``"autoload": {
        "AT Translated Set 2 keyboard": "new preset"
    },
    "macros": {
        "keystroke_sleep_ms": 10
    },
    "gamepad": {
        "joystick": {
            "non_linearity": 4,
            "pointer_speed": 80,
            "left_purpose": "mouse",
            "right_purpose": "wheel",
            "x_scroll_speed": 2,
            "y_scroll_speed": 0.5``

**Comment by sezanzeb** [comment]
What do you think could be a better name for the toggle?
